<%@ page contentType="text/html; charset=utf-8" language="java" import="java.util.*" import="java.sql.*" errorPage="" %>
<%java.text.DateFormat df = new java.text.SimpleDateFormat("ddMMyyyy"); %>
<%java.text.DateFormat df2 = new java.text.SimpleDateFormat("yyyy-MM-dd"); %>
<%java.text.DateFormat df3 = new java.text.SimpleDateFormat("HH:mm:ss"); %>
<%

    Class.forName("org.gjt.mm.mysql.Driver");
    Connection conn_001 = DriverManager.getConnection("jdbc:mysql://localhost/inv_cs", "root", "eve9397");

    ResultSet rset = null;
    Statement stmt = null;
    stmt = conn_001.createStatement();

    String but = "", clave = "", descrip = "", present = "", id_med = "", cs_jv = "", descr_jv = "";

    String ope = request.getParameter("op");
    String uni = request.getParameter("uni");
    String cv_uni = request.getParameter("cv_uni");
    String cv_inv = request.getParameter("cv_inv");
    String tipo = request.getParameter("tipo");
    String clave_inventario = request.getParameter("cv_inv");

    try {
        but = "" + request.getParameter("submit");
        //out.print(but);
    } catch (Exception e) {
        System.out.print("not");
    }

    if (but.equals("Clave")) {
        cs_jv = request.getParameter("clave_med");
        String qry_cen_sad = "select * from clave_med where clave = '" + cs_jv + "'";

        rset = stmt.executeQuery(qry_cen_sad);
        while (rset.next()) {
            clave = rset.getString("clave");
            descrip = rset.getString("descrip");
            present = rset.getString("present");
            id_med = rset.getString("id_med");
        }
    }

    if (but.equals("Descripcion")) {
        descr_jv = request.getParameter("country");
        String qry_cen_sad = "select * from clave_med where descrip = '" + descr_jv + "'";
        out.print(qry_cen_sad);
        rset = stmt.executeQuery(qry_cen_sad);
        while (rset.next()) {
            clave = rset.getString("clave");
            descrip = rset.getString("descrip");
            present = rset.getString("present");
            id_med = rset.getString("id_med");
        }
    }

    if (but.equals("Capturar")) {

        String c_op = request.getParameter("op");
        String c_cvuni = request.getParameter("cv_uni");
        String c_desc = request.getParameter("descrip");
        String c_cvmed = request.getParameter("clave");
        String c_present = request.getParameter("present");
        String c_idmed = request.getParameter("tipo_med");
        String c_cant = request.getParameter("cant");
        String c_lote = request.getParameter("lote");
        String c_cadu = request.getParameter("cadu");

        if (c_cvmed.equals("") || c_cant.equals("")) {
%>
<script>alert("Medicamento Invalido");</script>
<%
        } else {
            String qry_cen_sad = "insert into inventarios (clave_inv, clave_uni, clave, fecha, fecha_cad, lote, cantidad, operador, costo, hora) values ( '" + cv_inv + "', '" + c_cvuni + "', '" + c_cvmed + "', '" + df2.format(new java.util.Date()) + "', '" + c_cadu + "', '" + c_lote + "', '" + c_cant + "', '" + c_op + "', '---', '" + df3.format(new java.util.Date()) + "' )";
            stmt.execute(qry_cen_sad);
            //out.print(qry_cen_sad);
        }

    }


%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<script>
    function focus_locus() {
        if (document.form1.clave.value == "") {
            document.form1.clave_med.focus();
        } else {
            document.form2.cant.focus();
        }
    }
    function tufuncion(e) {
        tecla = (document.all) ? e.keyCode : e.which;
        if (tecla == 13) {
            document.getElementById("Capturar").focus();
        }
    }
</script>
<script src="jqry/ui/jquery-1.8.3.js"></script>
<script src="jqry/ui/jquery-ui.js"></script>
<script src="jqry/ui/jquery.ui.autocomplete.js"></script>
<link rel="stylesheet" href="jqry/themes/base/jquery-ui.css"/>

<script>
var data = [
    "ACIDO ACETILSALICILICO TABLETAS 500MG ENVASE C/20 TABLETAS ",
    "ACIDO ACETILSALICILICO TABLETA SOLUBLE O EFERVESCENTE 300 MG",
    "PARACETAMOL TABLETA 500 MG",
    "PARACETAMOL SUPOSITORIO 300 MG",
    "PARACETAMOL (ACETAMINOFEN) SOLUCION ORAL 100MG/ML /ENVASE CON GOTERO DE 15ML",
    "METAMIZOL SODICO COMPRIMIDO 500 MG",
    "METAMIZOL SODICO SOLUCION INYECTABLE 1 G/2 MLL",
    "BUTILHIOSCINA/METAMIZOL GRAGEAS 10MG/250 MG 36 GRAGEAS",
    "NALBUFINA SOLUCION INYECTABLE 10 MG/ML",
    "DIAZEPAM SOLUCION INYECTABLE AL 10% 10 MG/ 2ML",
    "ATROPINA SOLUCION INYECTABLE 1 MG/ML",
    "TIOPENTAL SODICO SOLUCION INYECTABLE 0 5 G/20ML",
    "KETAMINA SUSPENSION INYECTABLE 500 MG/10ML",
    "SEVOFLURANO LIQUIDO 250 ML",
    "FENTANILO SOLUCION O EMULSION INYECTABLE 0 5 MG/10ML",
    "ETOMIDATO SOLUCION INYECTABLE 20MG/10ML 5 AMPOLLETAS CON 10ML",
    "PROPOFOL EMULSION INYECTABLE 200MG/20ML 5 AMPOLLETAS O FRASCOS AMPULA DE 20ML",
    "DEXMEDETOMIDINA SOLUCION INYECTABLE 200MG 1 5 Y 25 FRASCOS AMPULA",
    "DEXMEDETOMIDINA SOLUCION INYECTABLE 200MG 1 FRASCO AMPULA",
    "DEXMEDETOMIDINA SOLUCION INYECTABLE 200MG 25 FRASCOS AMPULA",
    "SUXAMETONIO CLORURO DE SOLUCION INYECTABLE 40 MG/2 ML",
    "VECURONIO SOLUCION INYECTABLE 4 MG/1 ML",
    "LIDOCAINA GEL 20 MG/ML ENVASE CON 10 ML",
    "LIDOCAINA SUSPENSION ORAL 500 MG/50 ML ",
    "LIDOCAINA SOLUCION INYECTABLE AL 2% 1 G/50ML",
    "LIDOCAINA SUSPENSION ORAL 1 G/50ML",
    "LIDOCAINA SOLUCION INYECTABLE AL 1% 100 MG/2 ML",
    "LIDOCAINA 10% SPRAY 10G  ENVASE C/115ML ",
    "LIDOCAINA 2% C/EPINEFRINA 0 25MG SOLUC  INYECTABLE  1G  ENVASE C/5 FRASCO-AMPULA 50ML ",
    "LIDOCAINA EPINEFRINA SOLUCION INYECTABLE AL 2% CADA CARTUCHO DENTAL CONTIENE: CLORHIDRATO DE LIDOCAINA 36 MG EPINEFRINA (1:100000) 0 018 MG ENVASE CON",
    "ROPIVACAINA 40MG SOLUCION INYECTABLE ENVASE CON 5 AMPULAS DE 20 ML",
    "ROPIVACAINA 150MG SOLUCION INYECTABLE ENVASE CON 5 AMPULAS DE 20ML",
    "BUPIVACAINA SOLUCION INYECTABLE 5 MG/ML",
    "NEOSTIGMINA SOLUCION INYECTABLE 0 5 MG/ML",
    "NALOXONA SOLUCION INYECTABLE 0 4 MG/ML",
    "CLORFENAMINA TABLETA 4 MG",
    "DIFENHIDRAMINA JARABE 12 5 MG/5ML",
    "DIFENHIDRAMINA POLVO 100 MG/10ML",
    "CLORFENAMINA JARABE 0 5 MG/ML",
    "AMINOFILINA SOLUCION INYECTABLE 250 MG/10ML",
    "SALBUTAMOL SUSPENSION 20 MG",
    "SALBUTAMOL JARABE 2 MG/5 ML",
    "TERBUTALINA SOLUCION INYECTABLE 0 25 MG/ML",
    "TERBUTALINA TABLETA 5MG",
    "TEOFILINA COMPRIMIDO O TABLETA O CAPSULA DE LIBERACION PROLONGADA 100 MG",
    "TERBUTALINA POLVO 0 5 MG/DOSIS",
    "SALBUTAMOL SOLUCION ORAL 0 5 G/ 100 ML",
    "CROMOGLICATO DE SODIO SUSPENSION 3 6 G/100 G",
    "PREDNISONA TABLETA 5 MG",
    "PREDNISONA TABLETA 50 MG",
    "HIDROCORTISONA SOL  INY  100MG/2ML ENVASE C/50 FCO-AMP  Y DILUYENTE DE 2ML ",
    "METILPREDNISOLONA SOLUCION INYECTABLE 500MG/8ML",
    "BECLOMETASONA DIPROPIONATO DE SUSPENSION AEROSOL 10 MG/INHALADOR",
    "DIGOXINA TABLETA 0 25 MG",
    "DIGOXINA ELIXIR 0 05 MG/ML",
    "DIGOXINA SOLUCION INYECTABLE 0 5 MG/2 ML",
    "PARACETAMOL SUPOSITORIO 100 MG",
    "LIDOCAINA SOLUCION INYECTABLE AL 5 % 100 MG/5 ML",
    "POTASIO SALES DE TABLETAS SOLUBLE BICARBONATO DE K+ 766MG BITRATO DE K+460 MG 50 TABLETAS SOLUBLES",
    "CLORURO DE POTASIO SOLUCION INYECTABLE 1 49 G/ 10 ML",
    "FENITOINA TABLETA O CAPSULA 100 MG",
    "PROPRANOLOL TABLETA 40 MG",
    "PROPRANOLOL TABLETA 10 MG",
    "CLORTALIDONA TABLETA 50 MG",
    "METILDOPA TABLETA 250 MG",
    "DIAZOXIDO SOLUCION INYECTABLE 300MG/20ML AMPOLLETA CON 20ML",
    "NITROPRUSIATO DE SODIO SOLUCION INYECTABLE 50 MG",
    "HIDRALAZINA TABLETA 10 MG",
    "METOPROLOL TABLETA 100 MG",
    "PRAZOSINA CAPSULAS O COMPRIMIDOS1MG 30 CAPSULAS O COMPRIMIDOS",
    "CAPTOPRIL TABLETA 25 MG",
    "TRINITRATO DE GLICERILO CAPSULA O TABLETA MASTICABLE 0 8 MG",
    "ISOSORBIDA TABLETA SUBLINGUAL 5 MG",
    "ISOSORBIDA TABLETA 10 MG",
    "VERAPAMILO GRAGEA O TABLETA RECUBIERTA 80 MG",
    "NIFEDIPINO CAPSULA DE GELATINA BLANDA 10 MG",
    "VERAPAMILO SOLUCION INYECTABLE 5 MG/ 2 ML",
    "NIFEDIPINO COMPRIMIDO DE LIBERACION PROLONGADA 30 MG",
    "EPINEFRINA SOLUCION INYECTABLE 1 MG (1:1000)",
    "DOPAMINA SOLUCION INYECTABLE 200 MG/ 5 ML",
    "DOBUTAMINA SOLUCION INYECTABLE 250 MG",
    "HEPARINA SOLUCION INYECTABLE 10 000 UI/ 10 ML (1000UI/ML)",
    "HEPARINA SOLUCION INYECTABLE DE 25 000 U I/5ML (5000UI/ML) ENVASE C/ 50 FCO-AMPULA DE 5ML ",
    "WARFARINA TABLETA 5 MG",
    "ACENOCUMAROL TABLETA 4 MG",
    "FITOMENADIONA  EMULSION INYECTABLE  10MG/ML  3 AMPOLLETAS CON 1ML ",
    "DEXTRAN SOLUCION INYECTABLE DEXTRAN (40 000) 10 G/100 ML GLUCOSA5 G/ 100 ML",
    "BEZAFIBRATO TABLETA 200 MG",
    "PRAVASTATINA TABLETA 10 MG",
    "OXIDO DE ZINC PASTA 25 G/100 G",
    "HIDROCORTISONA CREMA 1 MG/G",
    "BENZOILO LOCION DERMICA O GEL DERMICO 5 G/100 ML O 5 G/100 G",
    "ALANTOINA Y ALQUITRAN DE HULLA SUSPENSION AEROSOL 20 MG/ML Y 9 4 MG/ML",
    "BENCILO EMULSION DERMICA 300 MG/ML",
    "ALIBOUR POLVO SULFATO DE COBRE 177 MG/G  SULFATO DE ZINC 619 5 MG/G  ALCANFOR 26 5 MG",
    "CLIOQUINOL CREMA 30 MG/G",
    "MICONAZOL CREMA 20 MG/1 G",
    "PODOFILINA SOLUCION DERMICA 250 MG/ML",
    "ACIDO RETINOICO CREMA 0 05 G/100 G",
    "CALCIO EFERVECENTE CAPS  500 MG ",
    "LEVOTIROXINA TABLETA 100 UÂµG",
    "TIAMAZOL TABLETA 5 MG",
    "GLIBENCLAMIDA TABLETA 5 MG",
    "INSULINA  HUMANA  ACCION INTERMEDIA NPH SOLUCION INYECTABLE 100 UI/ML",
    "INSULINA  HUMANA  ACCION RAPIDA REGULAR SUSPENSION INYECTABLE 100 UI/ML",
    "DANAZOL CAPSULA O COMPRIMIDO 100 MG",
    "CALCITRIOL CAPSULAS DE GELATINA BLANDA 0 25 UÂµG",
    "BROMOCRIPTINA TABLETA 2 5 MG",
    "VITAMINA A  C  D SOLUCION PALMITATO DE RETINOL 70009000 UI  AC  ASCORBICO 80-125 MG COLECALCIFERO L 1400 -1800 UI EN UN ML",
    "BUTILHIOSCINA GRAGEA 10 MG",
    "BUTILHIOSCINA SOLUCION INYECTABLE 20 MG/ML",
    "CISAPRIDA SUSPENSION ORAL 1MG/ML   SUSPENSION ORAL 100 MG/100 ML ENVASE CON 60 ML Y DOSIFICADOR ",
    "CISAPRIDA TABLETAS 5MG 30 TABLETAS",
    "ALUMINIO/MAGNESIO TABLETA MASTICABLE AL 200 MG 200 O 447 3 MG",
    "ALUMINIO Y MAGNESIO SUSPENSION 3 7/4G O 8 9/100ML ENVASE  C/240ML ",
    "RANITIDINA GRAGEA O TABLETA 150 MG",
    "RANITIDINA SOLUCION INYECTABLE 50MG",
    "METOCLOPRAMIDA SOL   INYECTABLE 10MG/2ML ENVASE  C/6 AMPOLLETAS DE 2ML ",
    "METOCLOPRAMIDA TABLETA 10 MG",
    "METOCLOPRAMIDA SOLUCION 4 MG/ML",
    "BISMUTO SUBSALICILATO SUSPENSION  1 750G/ 100ML  ENVASE C/240ML ",
    "SENOSIDOS A-B SOLUCION ORAL 200MG/100ML ENVASE CON 75 ML ",
    "PLANTAGO PSYLLIUM POLVO 49 7 G/100 G",
    "SENOSIDOS A-B TABLETA 8 6 MG",
    "METRONIDAZOL TABLETA 500 MG",
    "METRONIDAZOL SOLUCION INYECTABLE 200 MG/ 10 ML",
    "METRONIDAZOL SUSPENSION ORAL 250MG /5ML  ENVASE FRASCO C/120ML ",
    "METRONIDAZOL SOLUCION INYECTABLE 500 MG/100 ML",
    "QUINFAMIDA TABLETAS 300MG 1 TABLETA",
    "ALBENDAZOL TABLETA 200 MG",
    "ALBENDAZOL SUPOSITORIO 400 MG/20 ML",
    "ALBENDAZOL TABLETA 200 MG",
    "LIDOCAINA HIDROCORTISONA UNGUENTO 50 MG/2 5 MG/1 G",
    "LIDOCAINA-HIDROCORTISONA SUPOSITORIO 60MG/5G   ENVASE CON 6 SUPOSITORIOS",
    "ESTROGENOS CONJUGADOS TABLETAS O GRAGEAS 0 625 MG DE ESTROGENOS DE ORIGEN VEGETAL ENVASE  C/42 TABLETAS O GRAGEAS ",
    "ESTROGENOS CONJUGADOS DE ORIGEN EQUINO CREMA VAGINAL 0 625MG/G ENVASE CON 43G Y APLICADOR",
    "CARBETOCINA SOLUCION INYECTABLE 100 UÂµG",
    "OXITOCINA SOLUCION INYECTABLE 5 UI/ ML",
    "ERGOMETRINA (ERGONOVINA) SOLUCION INYECTABLE 0 2 MG/ ML",
    "ORCIPRENALINA SOLUCION INYECTABLE 0 5 MG/ ML",
    "ORCIPRENALINA TABLETA 20 MG",
    "METRONIDAZOL OVULO O TABLETA VAGINAL 500 MG",
    "NITROFURAL OVULO 6 MG",
    "NISTATINA OVULO O TABLETA VAGINAL 100 000 UI",
    "INMUNOGLOBULINA ANTI D SOLUCION INYECTABLE 0 300 MG",
    "ACIDO FOLICO TABLETA 4 MG",
    "FUMARATO FERROSO TABLETAS 200 MG",
    "FUMARATO FERROSO SUSPENSION ORAL 29 MG/ML L",
    "SULFATO FERROSO TABLETA 200 MG",
    "SULFATO FERROSO SOLUCION 125 MG/ ML",
    "HIERRO DEXTRAN  SOLUCION INYECTABLE  100MG/2ML  3 AMPOLLETAS ",
    "ACIDO FOLICO TABLETA 5 MG",
    "HIDROXOCOBALAMINA SOLUCION INYECTABLE 100 UÂµG/2 ML",
    "ACIDO FOLICO TABLETAS DE 0 4MG   ENVASE  C/90 TABLETAS",
    "FITOMENADIONA SOLUCION INYECTABLE 2 MG",
    "ESTREPTOQUINASA   SOLUCION INYECTABLE  1 500 000 UI  1 FRASCO AMPULA ",
    "METOTREXATO TABLETA 2 5 MG",
    "METOTREXATO SOLUCION INYECTABLE 500 MG",
    "TRIMETOPRIMA- SULFAMETOXAZOL TABLETA O COMPRIMIDO 80 MG Y 400 MG",
    "TRIMETROPIM-SULFAMETOXAZOL SUSPENSION 40 MG/200 MG/ 5 ML",
    "NITROFURANTOINA CAPSULA 100 MG",
    "BENCILPENICILINA SODICA SOLUCION INYECTABLE 1 000 000 UI",
    "BENCILPENICILINA PROCAINICA                      -BENCILPENICILINA CRISTALINA SUSPENSION EN AEROSOL 300 000 UI /100 000 UI",
    "BENCILPENICILINA PROCAINICA/ BENCILPENICILINA CRISTALINA SUSPENSION INYECTABLE 600 000UI/ 200 000 UI",
    "BENZATINA BENCILPENICILINA SUSPENSION INYECTABLE 1 200 000 UI",
    "DICLOXACILINA CAPSULA O COMPRIMIDO 500 MG",
    "DICLOXACILINA SUSPENSION 250 MG/ 5 ML",
    "DICLOXACILINA SOLUCION INYECTABLE 250 MG/5 ML",
    "AMPICILINA TABLETA O CAPSULA 500 MG",
    "AMPICILINA SUSPENSION 250 MG/ 5 ML",
    "AMPICILINA SOLUCION INYECTABLE 500 MG/2 ML",
    "BENCILPENICILINA    SODICA CRISTALINA SOLUCION INYECTABLE 5 000 000 UI",
    "CEFOTAXIMA SOL  INYECTABLE DE 1G/4ML ENVASE FRASCO-AMP  Y DILUYENTE DE 4ML ",
    "CEFTRIAXONA SOLUCION INYECTABLE 1 G/10 ML",
    "BENCILPENICILINA BENZATINICA COMPUESTA SUSPENSION INYECTABLE BENZATINICA 600 000 UI PROCAINICA 300000 UI CRISTALINA 300 000 UI",
    "CEFALEXINA TABLETA O CAPSULA 500 MG",
    "DOXICICLINA CAPSULA O TABLETA 100 MG",
    "DOXICICLINA CAPSULA O TABLETA 50 MG",
    "KANAMICINA SOLUCION INYECTABLE 1 G",
    "GENTAMICINA SOLUCION INYECTABLE 80 MG",
    "GENTAMICINA SOLUCION INYECTABLE 20 MG",
    "AMIKACINA SOLUCION INYECTABLE 500 MG/2 ML",
    "AMIKACINA SOLUCION INYECTABLE 100 MG/2 ML",
    "ERITROMICINA CAPSULA O TABLETA 500 MG",
    "ERITROMICINA SUSPENSION ORAL 250MG/5ML ENVASE FRASCO C/100ML ",
    "TETRACICLINA TABLETA O CAPSULA 250 MG",
    "CLORANFENICOL CAPSULA 500 MG",
    "AMFOTERICINA B  SOLUCION INYECTABLE  50MG  1 FRASCO AMPULA ",
    "KETOCONAZOL DE 200MG  C/10 TABLETAS",
    "ITRACONAZOL CAP 100 MG ",
    "ISOCONAZOL CREMA 1 G/100 G",
    "PRAZICUANTEL TABLETA 600 MG",
    "TRAMADOL-PARACETALTABLETA37 5 / 325 0MG 20 TABLETAS",
    "BUPRENORFINA PARCHE 30 MG",
    "BUPRENORFINA PARCHE 20 MG",
    "BUPRENORFINA TABLETA SUBLINGUAL 0 2 MG",
    "CLONIDINA COMPRIMIDO 0 1 MG",
    "MORFINA  SOLUCION INYECTABLE  10MG  5 AMPOLLETAS ",
    "MORFINA TABLETA     O     CAPSULA     DE     LIBERACION PROLONGADA 100 MG",
    "TRAMADOL SOLUCION INYECTABLE 100MG/2ML 5 AMPOLLETAS",
    "EFEDRINA  SOLUCION INYECTABLE  50MG/2ML  100 AMPOLLETAS CON 2ML ",
    "MIDAZOLAM  SOLUCION INYECTABLE  5MG/5ML  5 AMPOLLETAS CON 5ML ",
    "AMLODIPINO TABLETAS O CAPSULAS5MG 10 TABLETAS O CAPSULAS",
    "FELODIPINO TABLETAS DE LIBERACION PROLONGADA5MG 10 TABLETAS DE LIBERACION PROLONGADA",
    "HIDRALAZINA SOLUCION INYECTABLE 10 MG/ ML",
    "BETAMETASONA UNGUENTO 50 MG/100 G",
    "ACICLOVIR COMPRIMIDO O TABLETA 400 MG",
    "AMOXICILINA SUSPENSION ORAL DE 500MG/5ML ENVASE FRASCO C/75ML ",
    "AMOXICILINA CAPSULA 500 MG",
    "AMOXICILINA-ACIDO CLAVULANICO SUSPENSION 125 MG/ 31 25MG/5 ML",
    "AMOXICILINA-ACIDO CLAVULANICO SOLUCION INYECTABLE 500 MG/100 MG",
    "CEFACLOR CAPSULAS 250MG 15 CAPSULAS",
    "CLARITROMICINA TABLETA 250 MG",
    "FLUCONAZOL  SOLUCION INYECTABLE  100MG  FRASCO AMPULA CON 50ML ",
    "MEBENDAZOL TABLETA 100 MG",
    "PIRANTEL TABLETA 250 MG",
    "BETAMETASONA SOLUCION INYECTABLE 4 MG / ML",
    "CLORFENAMINA SOLUCION INYECTABLE 10 MG/ML",
    "LORATADINA TABLETA O GRAGEA 10 MG",
    "LORATADINA JARABE 5 MG/5 ML",
    "BUTILHIOSCINA/METAMIZOL SOLUCION INYECTABLE 2 5G/0 020G/5ML 5 AMPOLLETAS CON 5ML",
    "CISAPRIDA TABLETAS 10MG 30 TABLETAS",
    "RANITIDINA JARABE 150 MG/10 ML",
    "ACIDO FOLINICO SOLUCION INYECTABLE 15 MG/5 ML",
    "BETAMETASONA ACETATO DE Y BETAMETASONA FOSFATO DISODICO DE  SUSPENSION INYECTABLE  BETAMETASONA ACETATO DE 2 710MG/ML Y BETAMETASONA FOSFATO DISODICO ",
    "ENOXAPARINA SOLUCION INYECTABLE 40 MG/ 0 4 ML",
    "DEXTROMETORFANO JARABE 10MG/5ML ENVASE CON 120ML",
    "IPRATROPIO SUSPENSION EN AEROSOL 0 286 MG/G",
    "CEFACLOR SUSPENSION ORAL 7 5G 150ML (250MG/5ML)",
    "CARBAMAZEPINA TABLETA 400 MG",
    "CLARANFENICOL Y SULFACETAMIDA SODICA  SOL OFTALMICA 0 5G/100ML  10G/100ML",
    "PREDNISOLONA UNGUENTO OFTALMICO 5 MG/G",
    "PREDNISOLONA -SULFACETAMINA  SOL  OFTALMICA 5 MG/100ML ENVASE GOTERO INTEGRADO 10ML",
    "IPRATROPIO SOLUCION 0 25 MG/ ML",
    "IPRATROPIO -SALBUTAMOL SOLUCION 0 50 MG/2 50 MG/2 5 ML",
    "IPRATROPIO -SALBUTAMOL SUSPENSION EN AEROSOL 0 286 MG/1 423 MG/G",
    "VITAMINA A CAPSULA 50 000 UI",
    "PENICILAMINA TABLETAS 300MG 50 TABLETAS",
    "LEVONORGESTREL POLVO 52 MG",
    "LEVONORGESTREL COMPRIMIDO O TABLETA 0 750 MG",
    "AMOXICILINA-ACIDO CLAVULANICO TABLETA 500 MG/125 MG",
    "CARBON ACTIVADO POLVO 1 KG",
    "CINITAPRIDA COMPRIMIDO 1 MG",
    "CINITAPRIDA GRANULADO 1 MG",
    "BITARTRATO DE CINITRAPIDA SOLUCION ORAL 20MG/100ML (1MG/5ML) ENVASE C/120 ML Y CUCHARILLA DOSIFICADORA",
    "TIOTROPIO  BROMURO DE CAPSULA 18 UÂµG",
    "TIOTROPIO  BROMURO DE CAPSULA 18 UÂµG",
    "HIDROCLOROTIAZIDA TABLETA 25 MG",
    "ACETAZOLAMIDA TAB  250MG  ENVASE C/20 TABLETAS",
    "ACETAZOLAMIDA SOLUCION INYECTABLE 500 MG/ 5ML",
    "ESPIRONOLACTONA TAB  25MG ENVASE C/ 20 TABLETAS ",
    "MANITOL  SOLUCION INYECTABLE 20% 50G/250ML ENVASE C/250 ML ",
    "FUROSEMIDA TABLETA 40 MG",
    "FUROSEMIDA SOLUCION INYECTABLE 20MG/2ML   ENVASE C/5 AMPOLLETAS DE 2ML ",
    "FENAZOPIRIDINA TABLETAS 100MG 20 TABLETAS",
    "ESTREPTOMICINA SOLUCION INYECTABLE 1 G",
    "ISONIAZIDA TABLETA 100 MG",
    "ETAMBUTOL TABLETA 400 MG",
    "RIFAMPICINA SUSPENSION 100 MG/ 5 ML",
    "PIRAZINAMIDA TABLETA 500 MG",
    "ISONIAZIDA -RIFAMPICINA TABLETA RECUBIERTA 400 MG/300 MG",
    "ISONIAZIDA-RIFAMPICINA PIRAZINAMIDA-ETAMBUTOL TABLETA 75 MG /150 MG/ 400 MG /300 MG",
    "BENZONATATO PERLAS  100MG 20 PERLAS ",
    "AMBROXOL COMPRIMIDO 30 MG",
    "AMBROXOL SOLUCION 300 MG/100 ML",
    "CLORFENAMINA COMPUESTA TABLETAS PARACETAMOL 500MG CAFEINA 25MG FENILEFRINA 5 MG CLORFENAMINA 4 MG 10 TABLETAS",
    "ALPRAZOLAM TABLETA 2 MG",
    "ALPRAZOLAM TABLETA 0 25 MG",
    "ENALAPRIL  O  LISINOPRIL  O RAMIPRIL CAPSULA O TABLETA 10 MG",
    "ALOPURINOL TABLETA 100 MG",
    "KETOPROFENO CAPSULAS DE 100 MGS ENVASE CON 15 CAPSULAS",
    "BECLOMETASONA DIPROPIONATO DE SUSPENSION DERMICA 50 MG/INHALADOR",
    "BENCILPENICILINA PROCAINICA SOL/INY DE 2 400 000UI FRASCO AMPULA CON DILUYENTE ",
    "AMINOACIDOS CRISTALINOS  SOLUCION INYECTABLE  FRASCO CON 250ML",
    "AMINOACIDOS CRISTALINOS  SOLUCION INYECTABLE  FRASCO CON 500ML ",
    "NITAZOXANIDA TABLETA 200 MG",
    "LOSARTAN GRAGEA O COMPRIMIDO RECUBIERTO 50 MG",
    "TELMISARTAN TABLETA 40 MG",
    "TELMISARTAN- HIDROCLOROTIAZIDA TABLETA 80 0 MG/12 5 MG",
    "FENOBARBITAL TABLETA 100 MG",
    "FENOBARBITAL TABLETA 15 MG",
    "CARBAMAZEPINA TABLETA 200 MG",
    "CARBAMAZEPINA SUSPENSION ORAL 100 MG/5 ML",
    "FENITOINA TABLETA 30 MG",
    "FENITOINA SUSPENSION ORAL 37 5 MG/5 ML",
    "CLONAZEPAM TABLETA 2 MG",
    "CLONAZEPAM SOLUCION 2 5 MG/ ML",
    "CLONAZEPAM SOLUCION INYECTABLE 1 MG/ ML",
    "FENOBARBITAL ELIXIR 20 MG/5 ML",
    "ACIDO VALPROICO CAPSULA 250 MG",
    "VALPROATO DE MAGNESIO TABLETA CON CUBIERTA ENTERICA 185 6 MG",
    "VALPROATO DE MAGNESIO SOLUCION 186 MG/ML",
    "FENITOINA SODICA SOLUCION INYECTABLE DE 250 MG /5 ML  --(PARA USO EN CS EN EMERGENCIA OBSTETRICA)",
    "OXCARBAZEPINA GRAGEA 300 MG 20 GRAGEAS",
    "OXCARBAZEPINA GRAGEA 600 MG 20 GRAGEAS",
    "OXCARBAZEPINA SUSPENSION 6 G/100 ML 120 ML",
    "VALPROATO SEMISODICO TABLETA DE LIBERACION PROLONGADA 500 MG",
    "TRIHEXIFENIDILO TABLETA 5 MG",
    "BIPERIDENO TABLETA 2 MG",
    "BIPERIDENO SOLUCION INYECTABLE 5 MG/ML",
    "LEVODOPA Y CARBIDOPA TABLETA 250 MG/25 MG",
    "LEVODOPA Y CARBIDOPA TABLETA DE LIBERACION PROLONGADA 200/50 MG",
    "ACIDO ASCORBICO TABLETA 100 MG",
    "COMPLEJO B TABLETA  COMPRIMIDO O CAPSULA TIAMINA 100 MG PIRIDOXINA 5 MG CIANOCOBALA MINA 50 UMG",
    "VITAMINA E GRAGEAS O CAPSULAS DE GELATINA  400 MG 100",
    "VITAMINA E GRAGEAS O CAPSULAS DE GELATINA  400 MG 99 GRAGEAS",
    "NAFAZOLINA SOL  OFTALMICA  (1 MG/ML)",
    "CLORANFENICOL SOLUCION OFTALMICA 5 MG/ML",
    "CLORANFENICOL UNGUENTO OFTALMICO 5 MG/G",
    "NEOMICINA  POLIMIXINA B Y GRAMICIDINA  CADA ML  CONTIENE: SULFATO DE NEOMICINA EQUIVALENTE A 1 75 MG  DE NEOMICINA  SULFATO DE POLIMIXINA B EQUIVALENT",
    "NEOMICINA  POLIMIXINA B  Y BACITRACINA SOL-OFT  NEOMICINA 3 5MG  POLIMIXINA B 5000U BASITRACINA 40UG ENV C/3 5G",
    "GENTAMICINA  SOLUCION OFTALMICA  3 MG/ML  FRASCO GOTERO CON 5ML ",
    "SULFACETAMIDA SOL  OFTALMICA 0 1 G/ ML   ENVASE CON  GOTERO INTEGRAL C/ 5ML",
    "ACICLOVIR UNGUENTO OFTALMICO 3 G/100 G",
    "PREDNISOLONA SOLUCION OFTALMICA 5 MG/ML",
    "PILOCARPINA SOL  OFTALMICA AL 2%  20 MG/ML ENVASE GOTERO INTEGRAL 15ML",
    "PILOCARPINA SOLUCION OFTALMICA 40 MG/ ML",
    "TIMOLOL SOL OFTALMICA  5MG/ML ENVASE GOTERO C/5ML ",
    "ATROPINA SOL OFTALMICA 10MG/ML ENVASE GOTERO C/15ML",
    "ATROPINA UNGUENTO OFTALMICO 10 MG/G",
    "MEDROXIPROGESTERONA TABLETAS 10 MG",
    "MEDROXIPROGESTERONA SOL-INY 15MG/1ML",
    "DIFENIDOL TABLETA 25 MG",
    "DIFENIDOL SOLUCION INYECTABLE 40 MG/2 ML",
    "DIMENHIDRINATO TABLETAS 50MG 24 TABLETAS",
    "NEOMICINA  POLIMIXINA B  FLUOCINOLONA Y LIDOCAINA SUSPENSION O SOLUCION OTICA  NEOMICINA 350MG/100 ML POLIMIXINA B 1000 000 UI/100ML  FLUOCINOLONA 25M",
    "LEVOMEPROMAZINA TABLETA 25 MG",
    "TRIAZOLAM  TABLETAS  0 125MG  20 TABLETAS ",
    "DIAZEPAM TABLETA 10 MG",
    "TRIFLUOPERAZINA GRAGEA O TABLETA 5 MG",
    "PERFENAZINA SOLUCION INYECTABLE 5MG/ ML",
    "HALOPERIDOL TABLETA 5 MG",
    "HALOPERIDOL SOLUCION INYECTABLE AL 5% 5 MG/ML",
    "LITIO TABLETA 300 MG",
    "RISPERIDONA TABLETA 2 MG",
    "CLOZAPINA COMPRIMIDO 100 MG",
    "RISPERIDONA  SOLUCION ORAL 1 0 MG/ ML",
    "RISPERIDONA SUSPENSION INYECTABLE DE LIBERACION PROLONGADA 25 MG",
    "IMIPRAMINA GRAGEA O TABLETA 25 MG",
    "AMITRIPTILINA TABLETA 25 MG",
    "ATOMOXETINA CAPSULA 10 MG",
    "ATOMOXETINA CAPSULA 40 MG",
    "ATOMOXETINA CAPSULA 60 MG",
    "NAPROXENO TABLETA 250 MG",
    "COLCHICINA TABLETA 1 MG",
    "INDOMETACINA  SUPOSITORIOS 100 MG ENV 6  SUPOSITORIOS",
    "INDOMETACINA CAPSULA 25 MG",
    "PIROXICAM CAPSULAS O TABLETAS 20MG 20 CAPSULAS O TABLETAS",
    "DICLOFENACO CAPSULA O GRAGEA DE LIBERACION PROLONGADA 100 MG",
    "NAPROXENO SUSPENSION ORAL 125 MG/ 5 ML",
    "MELOXICAM 0 150G/100ML 40ML Y PIPETA DOSIFICADORA DE 5ML",
    "KETOROLACO TROMETAMINA SOLUCION INYECTABLE 30 MG",
    "DEXAMETASONA TABLETA 0 5 MG",
    "METILPREDNISOLONA SUSPENSION INYECTABLE 40 MG/ ML",
    "ALOPURINOL TABLETA 300 MG",
    "AZATRIOPINA TABLETA 50 MG",
    "GLUCOSA 5 % SOLUCION INYECTABLE 5 G/ 100 ML FRASCO CON 250 ML",
    "GLUCOSA 5 % SOLUCION INYECTABLE 5 G/ 100 ML FRASCO CON 1000 ML",
    "GLUCOSA SOLUCION INYECTABLE AL 10% GLUCOSA ANHIDRA 10 G/100 ML",
    "GLUCOSA SOLUCION INYECTABLE AL 10% GLUCOSA ANHIDRA 50 G/100 ML",
    "GLUCOSA 50 %SOLUCION INYECTABLE50 G/ 100 ML FRASCO AMPULA DE 50 ML",
    "CLORURO DE SODIO SOLUCION INYECTABLE AL 0 9% 0 9 G/100 ML",
    "CLORURO DE SODIO SOLUCION INYECTABLE AL 0 9% 0 9 G/100 ML",
    "CLORURO DE SODIO 0 9 % SOLUCION INYECTABLE 0 9 G/ 100 ML ENVASE CON 1000 ML",
    "CLORURO DE SODIO Y GLUCOSA SOLUCION INYECTABLE 0 9 G /100 ML Y 5 0 G /100ML ",
    "CLORURO DE SODIO 0 9 % Y GLUCOSA SOLUCION INYECTABLE 0 9 G/100 ML   5 G/ 100 ML FRASCO CON 500ML",
    "CLORURO DE SODIO 0 9 % Y GLUCOSA 5 % SOLUCION INYECTABLE CLORURO DE SODIO 0 9 G/ 100 ML GLUCOSA ANIDAR 5 G/ 100 ML ENVASE CON 1000 ML",
    "SOLUCION HARTMANN SOLUCION INYECTABLE NA 750MG K 39 25MG CA 13 62MG CLORURO 970MG LACTATO 615MG AGUA  250ML ENVASE CON 250 ML",
    "SOLUCION HARTMANN SOLUCION INYECTABLE NA 1500MG K 78 5 MG CA 27 25MG CLORURO 1940 MG LACTATO 1230 MG AGUA INYECTABLE 500ML ENVASE 500ML",
    "SOLUCION HARTMANN SOLUCION INYECTABLE NA 3000MG K 157MG CA 54 5MG CLORURO 3880 MG LACTATO 2460MG AGUA 1000 ML ENVASE CON 1000 ML",
    "FOSFATO DE POTASIO SOLUCION INYECTABLE POTASIO DIBASICO 1 550G/10ML  POTASIO MONOFASICO 0 300G/10ML 50 AMPOLLETAS CON 10ML",
    "BICARBONATO DE SODIO SOLUCION INYECTABLE AL0 075 % 3 75 G/50 ML",
    "BICARBONATO DE SODIO SOLUCION INYECTABLE AL0 075 % 0 75 G/10 ML",
    "GLUCONATO DE CALCIO SOLUCION INYEC  AL 10% (1GR/10ML) ENVASE C/50 AMPOLLETAS DE 10ML ",
    "ELECTROLITOS ORALES POLVO PARA SOLUCION GLUCOSA 20 G  KCL 1 5 G NACL 3 5 G  CITRATO TRISODICO 2 9 G",
    "GLUCOSA SOLUCION INYECTABLE AL 10% GLUCOSA ANHIDRA 5 G/100 ML",
    "GLUCOSA SOLUCION INYECTABLE AL 50 % GLUCOSA ANHIDRA 5 G/ 100 ML",
    "CLORURO DE SODIO  SOLUCION INYECTABLE AL 0 9% DE 0 9GR/100ML",
    "SULFATO DE MAGNESIO SOLUCION INYECTABLE 1G ENVASE  C/100  AMPULAS DE 10ML",
    "GLUCOSA 5 % SOLUCION INYECTABLE 5 G/ 100 ML ENVASE CON 500ML",
    "GLUCOSA SOLUCION INYECTABLE AL 0 05 GLUCOSA ANHIDRA O GLUCOSA 5 G / 100 ML O GLUCOSA MONOHIDRATADA EQUIVALENTE A 5 G DE GLUCOSA",
    "GLUCOSA SOLUCION INYECTABLE AL0 05 % GLUCOSA ANHIDRA O GLUCOSA 5 G / 100 ML O GLUCOSA MONOHIDRATADA EQUIVALENTE A 5 G DE GLUCOSA",
    "GELATINA SOLUCION INYECTABLE POLIGELINA 3 5G/100ML 500ML CON O SIN EQUIPO PARA SU ADMINISTRACION",
    "SEROALBUMINA HUMANA SOLUCION INYECTABLE 12 5 G/50 ML 50ML",
    "AGUA INYECTABLE SOLUCION INYECTABLE5ML100 AMPOLLETAS",
    "AGUA INYECTABLE SOLUCION INYECTABLE 10ML 100 AMPOLLETAS",
    "AGUA INYECTABLE SOLUCION INYECTABLE 500ML FRASCO AMPULA",
    "VITAMINA A CAP  200000 UI ENVASE CON 25 DOSIS ",
    "BUPRENORFINA SOLUCION INYECTABLE 0 30 MG/ML",
    "CLONIXINATO DE LISINA SOLUCION INYECTABLE 100MG/2ML 5 AMPOLLETAS",
    "MIDAZOLAM 15MG _SOL  INY CON 5 AMPULAS DE 3ML",
    "FLUMAZENIL SOLUCION O EMULSION INYECTABLE 0 5 MG/5 ML(0 1 MG/ML)",
    "BUPIVACAINA HIPERBARICA SOLUCION INYECTABLE BUPIVACAINA 15 MG DEXTROSA 240 MG",
    "ROCURONIO 50MG/5ML 12AMPULAS SOLUCION INY ",
    "ROCURONIO  BROMURO DE SOLUCION INYECTABLE 50 MG/5 ML",
    "CISATRACURIO  BESILATO DE SOLUCION INYECTABLE 10 MG/5 ML (2 MG/ML)",
    "IRBESARTAN TABLETA 150 MG",
    "IRBESARTAN TABLETA 300 MG",
    "AMIODARONA SOLUCION INYECTABLE 150 MG",
    "AMIODARONA TABLETA 200 MG",
    "TRINITRATO DE GLICERILO PARCHE 5 MG/DIA",
    "TRINITRATO DE GLICERILO SOLUCION INYECTABLE 50 MG/10 ML",
    "PENTOXIFILINA TAB  400MG ENVASE C/30 TABLETAS",
    "ISOSORBIDA DINITRATO DE SOLUCION INYECTABLE 1 MG/ ML",
    "SIMVASTATINA TAB 20MG C/10 TAB",
    "SULFADIAZINA DE PLATA CREMA 1 G/100 G",
    "MOMETASONA  UNG  100 0 MG ",
    "SUSPENSION PARA INHALACIONCADA 100 ML CONTIENEN: FUROATO DE MOMETASONA MONOHIDRATADAEQUIVALENTE A 0 050 G DE FUROATO DE  MOMETASONAANHIDRO ",
    "INSULINA   LISPRO   LISPRO    PROTAMINA   CADA   ML    CONTIENE:   INSULINA   LISPRO   (ORIGEN ADN   RECOMBINANTE)   25   UI   INSULINA   LISPRO   PRO",
    "INSULINA HUMANA DE ACCION INTERMEDIA LENTA  100UI/ML FCO-AMP 10ML",
    "INSULINA GLARGINA (3) SOLUCION INYECTABLE 3 64 MG/ML",
    "ACIDO ALENDRONICO TABLETA O COMPRIMIDO 10 MG",
    "INSULINA LISPRO (4) SOLUCION INYECTABLE 100 UI/ ML",
    "RALOXIFENO TABLETA 60 MG",
    "ACIDO ALENDRONICO TAB 70 Mg ENVASE CON 4 TABLETAS",
    "LOPERAMIDA COMPRIMIDO, TABLETA O GRAGEA CADA COMPRIMIDO, TABLETA O GRAGEA CONTIENE: CLORHIDRATO DE LOPERAMIDA 2 MG ENVASE CON 12 COMPRIMIDOS, TABLETAS O GRAGEAS.",
    "ACIDO URSODEOXICOLICO CAPSULA 250 MG ENVASE CON 50 CAPSULAS",
    "HIDRALAZINA  SOL  INY  20MG ENVASE C/5 AMPULAS DE 1ML",
    "INDOMETACINA SOLUCION INYECTABLE 1 MG/2 ML",
    "ENOXAPARINA SOLUCION INYECTABLE 60 MG/0 6 ML",
    "DEXAMETASONA SOLUCION INYECTABLE AL 6% 8 MG/2 ML",
    "ENOXAPARINA SOLUCION INYECTABLE 20 MG/ 0 2 ML",
    "CLOPIDOGREL GRAGEA O TABLETA 75 MG",
    "LEVOFLOXACINO SUSPENSION INYECTABLE 500 MG/100 ML",
    "LEVOFLOXACINO SOLUCION INYECTABLE 500MG FRASCO AMPULA O BOLSA FLEXIBLE CON 100ML",
    "VANCOMICINA SOLUCION INYECTABLE 500 MG",
    "CEFTAZIDIMA SOL. INYECTABLE 1G 1 FCO",
    "CIPROFLOXACINO CAPSULA O TABLETA 250 MG",
    "CIPROFLOXACINO SOLUCION INYECTABLE 200MG/100 ML",
    "NISTATINA SOLUCION AL 10 % 100 000 UI/ML",
    "OFLOXACINA TABLETA 400 MG",
    "ACICLOVIR COMPRIMIDO O TABLETA 200 MG",
    "ACICLOVIR SOLUCION INYECTABLE 250 MG",
    "LEVOFLOXACINO TABLETAS 500 MG",
    "FINASTERIDA GRAGEA O TABLETA RECUBIERTA 5 MG",
    "MONTELUKAST  5MG 20 COMPRIMIDOS MASTICABLES",
    "MONTELUKAST 10MG 30 COMPRIMIDOS RECUBIERTOS",
    "COMPRIMIDO RECUBIERTO CADA COMPRIMIDO CONTIENE: MONTELUKAST SODICO EQUIVALENTE A 10 MG  DE MONTELUKAST",
    "ZAFIRLUKAST 20MG ENVASE CON 28 TABLETAS",
    "VITAMINAS (POLIVITAMINAS) Y MINERALES TABLETA  CAPSULA O GRAGEA VITAMINA B1  B2  B6  B12  NIACINAMIDA  E  A  D3  ACIDO PANTOTENICO  SULFATO FERROSO  C",
    "TETRACAINA SOLUCION OFTALMICA 5 MG/ ML",
    "DACTINOMICINA SOLUCION INYECTABLE 0 5 MG",
    "METILFENIDATO TABLETA DE LIBERACION PROLONGADA 18 MG",
    "METILFENIDATO TABLETA DE LIBERACION PROLONGADA 27 MG",
    "METILFENIDATO TABLETA DE LIBERACION PROLONGADA 36 MG",
    "HALOPERIDOL 2MG/ML FRASCO GOTERO 15ML SOLUCION ORAL",
    "HALOPERIDOL SOLUCION INYECTABLE AL 5% 50 MG/ML",
    "FLUOXETINA CAPSULA O TABLETA 20 MG",
    "SERTRALINA CAPSULA O TABLETA 50 MG",
    "DULOXETINA 60MG CON 14 CAPSULAS",
    "VENLAFAXINA CAPSULA O GRAGEA DE LIBERACION PROLONGADA 75 MG",
    "OLANZAPINA 10MG FRASCO AMPULA SOL  INY",
    "ARIPIPRAZOL TABLETA 15 MG",
    "ARIPIPRAZOL TABLETA 20 MG",
    "ARIPIPRAZOL TABLETA 30 MG",
    "SULFASALAZINA TABLETAS CON CAPA ENTERICA 500 MG",
    "DEXTRAN SOLUCION INYECTABLE DEXTRAN (60 000) 6 G/100 ML CLORURO DESODIO 7 5 G/ 100 ML",
    "TEOFILINA ELIXIR 533 MG/100 ML",
    "ADENOSINA SOLUCION INYECTABLE 6 MG",
    "ATORVASTATINA TABLETA 20 MG",
    "VALSARTAN 80MG 30 CAPSULAS",
    "METFORMINA TABLETA 850 MG",
    "ACARBOSA 50MG 30 TABLETAS",
    "SUCRALFATO TABLETA 1 G",
    "OMEPROZOL TAB O CAP 20 MG ",
    "PANTOPRAZOL 40MG GRAGEAS CON 7",
    "PANTOPRAZOL O RABEPRAZOL U OMEPRAZOL TABLETA O GRAGEA O CAPSULA PANTOPRAZOL 40 MG O RABEPRAZOL 20 MG U OMEPRAZOL 20 MG",
    "OMEPRAZOL O PANTOPRAZOL SOLUCION INYECTABLE OMEPRAZOL 40 MG O PANTOPRAZOL 40 MG",
    "ACIDO ASCORBICO  SOLUCION INYECTABLE  1G  6 AMPOLLETAS CON 10ML ",
    "PIRIDOXINA TABLETA  DE 300 MGS ENVASE CON 10 TABLETAS",
    "ACIDO FOLINICO TABLETA DE 15 MG ENVASE CON 12 TABLETAS",
    "TRIMETOPRIMA- SULFAMETOXAZOL SOLUCION INYECTABLE 160 MG Y 800 MG",
    "CEFALOTINA SOLUCION INYECTABLE 1 G/5 MG",
    "CLORANFENICOL SUSPENSION 31 25 MG/ML",
    "IMIPENEM Y CILASTATINA SOLUCION INYECTABLE 500 MG/ 500 MG",
    "CEFEPIME SOLUCION INYECTABLE 500 MG  EL FRASCO AMPULA CONTIENE CLORHIDRATO MONOHIDRATADO DE CEFEPIMA EQUIVALENTE A 500 MG  DE CEFEPIMA CON UN FRASCO A",
    "IMIPENEM Y CILASTATINA SOLUCION INYECTABLE 250 MG/250 MG",
    "MEROPENEM 500MG SOL  INY  1 FRASCO",
    "MEROPENEM 1G 1 FRASCO AMPULA",
    "CEFEPIMA SOLUCION INYECTABLE 1 G/3 O 10 ML",
    "NITROFURANTOINA SUSPENSION 25 MG/5 ML",
    "BERACTANT  25MG/ML FRASCO AMPULA 8ML",
    "METILFENIDATO COMPRIMIDO 10 MG",
    "VALPROATO DE MAGNESIO TABLETA DE LIBERACION PROLONGADA 600 MG",
    "VITAMINAS (POLIVITAMINAS) Y MINERALES JARABE VITAMINA A  D  E  C  B1  B2  B6  B12 NICOTINAMINA Y HIERRO",
    "POLIVITAMINAS SOLUCION INYECTABLE VITAMINAS FRASCO AMPULA Y DILUYENTE CON 5ML",
    "MULTIVITAMINAS SOLUCION INYECTABLE INFANTIL",
    "CLORURO DE SODIO 17 7 % SOLUCION INYECTABLE 0 177G/ML 100 AMPOLLETAS CON 10 ML",
    "TIAMINA SOLUCION INYECTABLE 500 MG",
    "CINARIZINA TABLETAS 75 MG 60 TABLETAS",
    "LEVOMEPROMAZINA SOLUCION INYECTABLE 25 MG/ ML",
    "LORAZEPAM TABLETA 1 MG",
    "PAROXETINA TABLETA 20 MG",
    "ZUCLOPENTIXOL SOLUCION INYECTABLE 200 MG",
    "ZUCLOPENTIXOL TABLETA 25 MG",
    "ZUCLOPENTIXOL  TABLETAS  25MG  50 TABLETAS ",
    "OLANZAPINA TABLETA 5 MG",
    "OLANZAPINA TABLETA 10 MG",
    "CITALOPRAM TABLETA 20 MG",
    "QUETIAPINA TABLETA 100 MG",
    "DICLOFENACO SOLUCION INYECTABLE 75 MG/3 ML",
    "LEVAMISOL 50MG TABLETAS CON 2",
    "CELECOXIB CAPSULAS 200MG 10 CAPSULAS",
    "ETEXILATO DE DABIGATRAN  TABS DE 110 MG",
    "SONDA PARA ASPIRAR SECRECIONES NO  8 ",
    "BOLSA FRACCIONADORA DE SANGRE (NEONATAL)",
    "TUBO ENDOTRAQUEAL 3 5 CON GLOBO 14 FR",
    "TUBO ENDOTRAQUEAL 4 5 CON GLOBO 18 FR",
    "TUBO ENDOTRAQUEAL 4 0 CON GLOBO 16 FR",
    "TUBO ENDOTRAQUEAL 3 0 CON GLOBO 12 FR",
    "GEL CONDUCTOR P/ULTRASONIDO ",
    "CIRCUITO PARA VENTILADOR ADULTO",
    "CIRCUITO PARA VENTILADOR PEDIATRICO",
    "SONDAS P/ASPIRAR SECRECIONES INFANTIL  NO  16",
    "SABANA DESECHABLE",
    "BATA PARA PACIENTE DESECHABLE ADULTO",
    "BATA PARA PACIENTE DESECHABLE PEDIATRICO",
    "VENDA SMARCH 10",
    "SONDA PARA ASPIRAR SECRECIONES NO  5",
    "LAPIZ PARA ELECTROCAUTERIO",
    "SUTURA VICRYL # 5",
    "CATETER PARA SUMINISTRO OXIGENO NEONATAL",
    "BOLSA FRACCIONADORA PARA COMPONENTES SANGUINEOS 150ML ",
    "SONDA FOLEY 16 TRES VIAS",
    "NYLON 1/0",
    "ABATELENGUAS DE MADERA  DESECHABLES LARGO: 142 0 MM  ANCHO:18 0 MM ",
    "AGUA OXIGENADA EN CONCENTRACION DEL 2 5 A 3 5 %",
    "AGUJA PARA ANESTESIA EPIDURAL  DE PAREDES DELGADAS  TIPO: TUOHY LONGITUD: 7 5 A 8 6 CM  CALIBRE: 16 G ",
    "AGUJA P/RAQUIANESTESIA C/MANDRIL 7 5 A 8 8 CAL 21G",
    "AGUJA PARA RAQUIANESTESIA O PUNCION LUMBAR  CON MANDRIL  DESECHABLES ESTERILES  LONGITUD: 7 5 A 8 8 CM  CALIBRE: 23 G ",
    "AGUJA PARA RAQUIANESTESIA O BLOQUEO SUBARACNOIDEO  DE ACERO INOXIDABLE  PUNTA TIPO LAPIZ  CONECTOR ROSCADO LUER LOCK HEMBRA TRANSLUCIDO Y MANDRIL CON ",
    "AGUJA HIPODERMICA HIPODERMICAS CON PABELLON LUER-LOCK HEMBRA DE PLASTICO  DESECHABLES  LONGITUD: 32 MM  CALIBRE: 20 G ",
    "AGUJA HIPODERMICA HIPODERMICAS CON PABELLON LUER-LOCK HEMBRA DE PLASTICO  DESECHABLES  LONGITUD: 32 MM  CALIBRE: 21 G ",
    "AGUJA HIPODERMICA CAL 25 G LONG 16 MM",
    "AGUJA HIPODERMICA HIPODERMICAS CON PABELLON LUER-LOCK HEMBRA DE PLASTICO  DESECHABLES  LONGITUD: 32 MM  CALIBRE: 22 G",
    "AGUJA PARA BIOPSIA  DESECHABLES  TIPO: TRUCUT LONGITUD: 9 65 CM  CALIBRE: 14 G ",
    "ALGODON EN LAMINAS  ENROLLADO O PLISADO  ",
    "JABON PARA USO PREQUIRURGICO LIQUIDO Y NEUTRO (PH 7) ",
    "ANTISEPTICO IODOPOVIDONA  ESPUMA  CADA 100 ML CONTIENEN: IODOPOVIDONA 8 G  EQUIVALENTE A 0 8 G DE YODO ",
    "ANTISEPTICO IODOPOVIDONA  ESPUMA CADA 100 ML CONTIENEN:IODOPOVIDONA 8 G EQUIVALENTE A 0 8 G DE YODO ",
    "ANTISEPTICO IODOPOVIDONA  SOLUCION CADA 100 ML CONTIENEN:IODOPOVIDONA 11 G EQUIVALENTE A 1 1 G DE YODO ",
    "ANTISEPTICO CLORURO DE BENZALCONIO AL 12 %  CADA 100 ML CONTIENEN: CLORURO DE BENZALCONIO 12 G  NITRITO DE SODIO (ANTIOXIDANTE) 5 G ",
    "DESINFECTANTES GLUTARALDEHIDO AL 2%  CON ACTIVADOR EN POLVO (COLOR VERDE AL ACTIVARSE) CON EFECTIVIDAD DE 14 DIAS  ",
    "ANTISEPTICOS ALCOHOL DESNATURALIZADO  ",
    "DETERGENTE O LIMPIADOR ENZIMATICO  CON ACTIVIDAD PROTEOLITICA  CONCENTRADO  PARA UTILIZARSE EN INSTRUMENTAL Y EQUIPO MEDICO  POLVO:SOBRE EN POLVO CON ",
    "DETERGENTES O LIMPIADORES DETERGENTE ENZIMATICO  CON ACTIVIDAD PROTEOLITICA  CONCENTRADO  PARA UTILIZARSE EN INSTRUMENTAL Y EQUIPO MEDICO LIQUIDO: FR",
    "DESINFECTANTES SOLUCION CONCENTRADA ESTERILIZANTE EN FRIO DEL 8 AL 12 5% DE GLUTARALDEHIDO  PARA PREPARAR UNA DILUCION DE USO FINAL DEL 2 AL 3 5%  PAR",
    "GLUTARALDEHIDO AL 2% ACTIVADO  DE COLOR VERDE LISTO PARA SU USO  CON EFECTIVIDAD DE 30 DIAS ",
    "APOSITO TRANSPARENTE  MICROPOROSO  AUTOADHERIBLE  ESTERIL Y DESECHABLE MEDIDAS: 10 0 A 10 16 X 12 0 A 14 0 CM ",
    "APOSITOS COMBINADOS DE CELULOSA 20 CM X 13 CM  ",
    "ALGODON TORUNDAS ",
    "BOLSA PARA UROCULTIVO (NINO)  ESTERIL  DE PLASTICO GRADO MEDICO  FORMA RECTANGULAR  CON CAPACIDAD DE 50 ML Y ESCALA DE 10  20  30 Y 50 ML  CON ORIFICI",
    "BOLSA PARA ENEMA  CAPACIDAD 1500 ML CON TUBO TRANSPORTADOR DE 5 0 A 6 0 MM DE DIAMETRO INTERNO  128 CM DE LONGITUD Y DISPOSITIVO OBTURADOR DE PLASTICO",
    "BOLSA PARA UROCULTIVO (NIÃ‘A)  ESTERIL  DE PLASTICO GRADO MEDICO  FORMA RECTANGULAR  CON CAPACIDAD DE 50 ML Y ESCALA DE 10  20  30 Y 50 ML  CON ORIFICI",
    "BOLSA PARA ILEOSTOMIA O COLOSTOMIA  TAMANO ADULTO  AUTOADHERIBLE  DE PLASTICO GRADO MEDICO  SUAVE  TRANSPARENTE  A PRUEBA DE OLOR  DRENABLE  EN FORMA ",
    "PARA ILEOSTOMIA O COLOSTOMIA  TAMANO INFANTIL AUTOADHERIBLE  DE PLASTICO GRADO MEDICO  SUAVE  TRANSPARENTE  A PRUEBA DE OLOR  DRENABLE  EN FORMA DE B",
    "BOLSA BALON RESPIRATORIO DE LATEX  COLOR NEGRO ELECTROCONDUCTOR CON DOS PLIEGUES PARA PARATO DE ANESTESIADIAMETRO INTERNO: 22 MM  CAPACIDAD 1 LT ",
    "BOLSA BALON RESPIRATORIO DE LATEX  COLOR NEGRO ELECTROCONDUCTOR CON DOS PLIEGUES PARA PARATO DE ANESTESIADIAMETRO INTERNO: 22 MM  CAPACIDAD 2 LT ",
    "BOLSA BALON RESPIRATORIO DE LATEX  COLOR NEGRO ELECTROCONDUCTOR CON DOS PLIEGUES PARA PARATO DE ANESTESIADIAMETRO INTERNO: 22 MM  CAPACIDAD 3 LT ",
    "BOLSA BALON RESPIRATORIO DE LATEX  COLOR NEGRO ELECTROCONDUCTOR CON DOS PLIEGUES PARA PARATO DE ANESTESIADIAMETRO INTERNO: 22 MM  CAPACIDAD 3 5 LT ",
    "BOLSA BALON RESPIRATORIO DE LATEX  COLOR NEGRO ELECTROCONDUCTOR CON DOS PLIEGUES PARA PARATO DE ANESTESIADIAMETRO INTERNO: 22 MM  CAPACIDAD 5 LT ",
    "BOLSA PARA RECOLECCION DE ORINA  RECTANGULAR  ELABORADA A BASE DE CLORURO DE POLIVINILO  CON GRADUACIONES CADA 100 ML Y LECTURA CADA 200 ML  SISTEMA C",
    "BOLSA AMARILLA PARA R P B I 90 X 120 CM",
    "BOLSA PARA ALIMENTACION PARENTERAL  PARA ADULTO  DE 3 LITROS  ESTERIL  ATOXICA DE ETILVINIL ACETATO  CON CAPSULA DE INYECCION PARA MEDICAMENTOS  CON C",
    "BOLSA ROJA PARA R P B I 50 X 65 CM",
    "BOLSA AMARILLA PARA R P B I 50 X 65 CM",
    "BOLSA AMARILLA PARA R P B I 50 X 65 CM",
    "BOTA BOTA QUIRURGICA DE TELA NO TEJIDA 100% DE POLIPROPILENO  TIPO SMS  DE 35 G/M2 MINIMO  IMPERMEABLE A LA PENETRACION DE LIQUIDOS Y FLUIDOS  ANTIEST",
    "BRAZALETE PARA IDENTIFICACION  DE PLASTICO  ADULTO ",
    "BRAZALETE PARA IDENTIFICACION  DE PLASTICO  INFANTIL ",
    "CAL SODADA  CON INDICADOR ",
    "CATETER PARA VENOCLISIS  DE FLUOROPOLIMEROS (POLITETRAFLUORETILENO  FLUORETILENPROPILENO Y ETILENTRIFLUORETILENO) O POLIURETANO  RADIOPACO  CON AGUJA ",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE CLORURO DE POLIVINILO TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 12 FR  NO 3 0",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE CLORURO DE POLIVINILO TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 14 FR ",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE CLORURO DE POLIVINILO TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 16 FR ",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE CLORURO DE POLIVINILO TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 18 FR ",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE CLORURO DE POLIVINILO TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 20 FR ",
    "CANULA PARA DRENAJE TORACICO  ANGULADA CON MARCA RADIOPACA  LONGITUD: 45 CM  CALIBRE: 20 FR ",
    "CANULA PARA DRENAJE TORACICO ANGULADA CON MARCA RADIOPACA  LONGITUD: 45CM  CALIBRE: 28 FR ",
    "CANULA PARA DRENAJE TORACICO ANGULADA CON MARCA RADIOPACA  LONGITUD: 45CM  CALIBRE: 36 FR ",
    "CANULA PARA DRENAJE TORACICO ANGULADA CON MARCA RADIOPACA  LONGITUD: 45CM  CALIBRE: 40 FR ",
    "CATETER CATETER VENOSO CENTRAL  CALIBRE 4 FR  LONGITUD 30 CM  DE POLIURETANO O SILICON  RADIOPACO  CON DOS LUMENES INTERNOS DE 22 G  CON PUNTA FLEXIBL",
    "CATETER PARA DIALISIS PERITONEAL  DE INSTALACION SUBCUTANEA  BLANDO DE SILICON  CON DOS COJINETES DE POLIESTER O DACRON  CON CONECTOR  TAPON Y SEGURO ",
    "CATETER PARA DIALISIS PERITONEAL  DE INSTALACION SUBCUTANEA  BLANDO DE SILICON  CON DOS COJINETES DE POLIESTER O DACRON  CON CONECTOR  TAPON Y SEGURO ",
    "SONDA PARA ASPIRACION  DE PLASTICO TRANSPARENTE LIBRE DE PIROGENOS  ATOXICO  DE 55 CM DE LONGITUD CON VALVULA DE CONTROL DE ASPIRACION  CON PUNTA ROMA",
    "SONDA PARA ASPIRACION  DE PLASTICO TRANSPARENTE LIBRE DE PIROGENOS  ATOXICO  DE 55 CM DE LONGITUD CON VALVULA DE CONTROL DE ASPIRACION  CON PUNTA ROMA",
    "SONDA PARA ASPIRACION  DE PLASTICO TRANSPARENTE LIBRE DE PIROGENOS  ATOXICO  DE 55 CM DE LONGITUD CON VALVULA DE CONTROL DE ASPIRACION  CON PUNTA ROMA",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 0  LONGITUD: 50 MM ",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 2  LONGITUD: 70 MM ",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 4  LONGITUD: 90 MM ",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 6 LONGITUD:110 MM ",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 00 LONGITUD:40 MM ",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 1  LONGITUD: 60 MM ",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 3  LONGITUD: 80 MM ",
    "CANULA OROFARINGEAS  DE PLASTICO TRANSPARENTE  TIPO: GUEDEL/BERMAN  TAMANO: 5  LONGITUD: 100 MM ",
    "CATETER PARA EMBOLECTOMIA  ESTERILES Y DESECHABLES  MODELO: FOGARTY  LONGITUD: 80 CM  CALIBRE: 3FR ",
    "CATETER PARA EMBOLECTOMIA  ESTERILES Y DESECHABLES  MODELO: FOGARTY  LONGITUD: 80 CM  CALIBRE: 4FR ",
    "CATETER PARA VENOCLISIS NO 23",
    "CATETER PARA EMBOLECTOMIA  ESTERILES Y DESECHABLES  MODELO: FOGARTY  LONGITUD: 80 CM  CALIBRE: 5FR ",
    "SONDA DE LATEX  PUNTA REDONDA  TIPO: NELATON  LONGITUD: 40 CM  CALIBRE: 28 FR ",
    "SONDA DE LATEX  PUNTA REDONDA  TIPO: NELATON  LONGITUD: 40 CM   CALIBRE: 30FR ",
    "SONDA PARA SUMINISTRO DE OXIGENO  CON TUBO DE CONEXION Y CANULA NASAL  DE PLASTICO  CON DIAMETRO INTERNO DE 2 0 MM  LONGITUD 180 CM ",
    "CATETER PARA SUMINISTRO OXIGENO PEDIATRICO",
    "CATETER PARA CATETERISMO VENOSO CENTRAL  CALIBRE 7 FR X 20 CM DE LONGITUD DE POLIURETANO O SILICON  CON PUNTA FLEXIBLE  RADIOPACO  CON DOS LUMENES INT",
    "CATETER PARA CATETERISMO VENOSO CENTRAL  CALIBRE 7 FR X 20 CM DE LONGITUD DE POLIURETANO O SILICON  CON PUNTA FLEXIBLE  RADIOPACO  CON TRES LUMENES IN",
    "CATETER PARA CATETERISMO VENOSO CENTRAL  CALIBRE 5 FR X 20 CM DE LONGITUD  DE POLIURETANO O SILICON  CON PUNTA FLEXIBLE  RADIOPACO  CON LUMEN INTERNO ",
    "CATETERE PARA DILATACION DE VALVULAS CARDIACAS CON GLOBO 15 MM X 80 MM DE LARGO  LONGITUD: 100 CM  CALIBRE: 9 FR ",
    "PARA SUBCLAVIA  DE SILICON  DOBLE LUMEN  ESTERIL Y DESECHABLE  LONGITUD: 30 CM CALIBRE: 7 FR ",
    "SONDA PARA ALIMENTACION  DE PLASTICO TRANSPARENTE  ESTERIL Y DESECHABLE CON UN ORIFICIO EN EL EXTREMO PROXIMAL Y OTRO EN LOS PRIMEROS 2 CM  TAMANO: IN",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE ELASTOMERO DE SILICON TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 8 FR (2 0MM)",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE ELASTOMERO DE SILICON TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 10 FR  (2 5MM",
    "PARA ASPIRAR SECRECIONES  DE PLASTICO  CON VALVULA DE CONTROL  ESTERIL Y DESECHABLE TAMANO: ADULTO LONGITUD: 55 CM  CALIBRE: 18 FR  DIAMETRO EXTERNO:",
    "SONDA DE ASPIRACION DE SECRECIONES NO  10",
    "CANULA PARA TRAQUEOSTOMIA  ADULTO  DE CLORURO DE POLIVINILO  CON BALON  CURVADA  CINTA DE FIJACION  GLOBO DE BAJA PRESION Y ALTO VOLUMEN  RADIOPACA  C",
    "TUBO ENDOTRAQUEALES  DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES  DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES  DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALVULA",
    "TUBO ENDOTRAQUEALES  DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES  DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "TUBO ENDOTRAQUEALES DE PLASTICO GRADO MEDICO  CON MARCA RADIOPACA  ESTERILES  DESECHABLES  CON GLOBO DE ALTO VOLUMEN Y BAJA PRESION  INCLUYE UNA VALV",
    "SONDA PARA DRENAJE  EN FORMA DE T  DE LATEX  TIPO: KEHR  CALIBRE: 10 FR",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 3 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA GASTROINTESTINALES DESECHABLES Y CON MARCA RADIOPACA  TIPO: LEVIN  CALIBRE: 12 FR ",
    "CATETER PARA VENOCLISIS  DE PLASTICO  NO RADIOPACO  ESTERIL Y DESECHABLE  CON AGUJA Y CONECTOR PARA JERINGA LONGITUD: 25MM   CALIBRE: 18 G ",
    "SONDA GASTROINTESTINALES DESECHABLES Y CON MARCA RADIOPACA  TIPO: LEVIN  CALIBRE: 18 FR ",
    "CATETER PARA VENOCLISIS DE POLITETRAFLUORETILENO O POLIURETANO  CON AGUJA  NO RADIOPACO CON CONECTOR PARA JERINGA DE PLASCTICO  ESTERIL Y DESECHABLE  ",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE ELASTOMERO DE SILICON TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 14 FR  (3 5MM",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE ELASTOMERO DE SILICON TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 16 FR  (4 0MM",
    "TUBO ENDOTRAQUEALES  SIN GLOBO  DE ELASTOMERO DE SILICON TRANSPARENTE  GRADUADOS  CON MARCA RADIOPACA  ESTERILES Y DESECHABLES  CALIBRE: 18 FR  (4 5MM",
    "CATETER PARA VENOCLISIS  DE PLASTICO  NO RADIOPACO  ESTERIL Y DESECHABLE  CON AGUJA Y CONECTOR PARA JERINGA  LONGITUD 19MM  CALIBRE 19G ",
    "SONDA URETRALES PARA IRRIGACION CONTINUA  DE LATEX  CON GLOBO DE 30 ML Y VALVULA  TIPO: FOLEY-OWEN (DE 3 VIAS)  CALIBRE: 18 FR ",
    "SONDAS URETRALES PARA IRRIGACION CONTINUA  DE LATEX  CON GLOBO DE 30 ML Y VALVULA  TIPO: FOLEY-OWEN (DE 3 VIAS)  18 FR ",
    "SONDA URETRALES PARA IRRIGACION CONTINUA  DE LATEX  CON GLOBO DE 30 ML Y VALVULA  TIPO: FOLEY-OWEN (DE 3 VIAS)  CALIBRE: 22 FR ",
    "SONDA DE LATEX  PUNTA REDONDA  TIPO: NELATON  LONGITUD: 40 CM  CALIBRE: 12 FR ",
    "SONDA DE LATEX  PUNTA REDONDA  TIPO: NELATON  LONGITUD: 40 CM  CALIBRE: 14 FR ",
    "CATETERE PARA VENOCLISIS  DE FLUOROPOLIMEROS (POLITETRAFLUORETILENO  FLUORETILENPROPILENO Y ETILENTRIFLUORETILENO) O POLIURETANO  RADIOPACO  CON AGUJA",
    "SONDA DE LATEX  PUNTA REDONDA  TIPO: NELATON  LONGITUD: 40 CM  CALIBRE: 16 FR ",
    "CATETERE PARA VENOCLISIS  DE FLUOROPOLIMEROS (POLITETRAFLUORETILENO  FLUORETILENPROPILENO Y ETILENTRIFLUORETILENO) O POLIURETANO  RADIOPACO  CON AGUJA",
    "CATETER PARA VENOCLISIS NO 21",
    "SONDA DE LATEX  PUNTA REDONDA  TIPO: NELATON  LONGITUD: 40 CM  CALIBRE: 18 FR ",
    "CATETER PARA VENOCLISIS  DE FLUOROPOLIMEROS (POLITETRAFLUORETILENO  FLUORETILENPROPILENO Y ETILENTRIFLUORETILENO) O POLIURETANO  RADIOPACO  CON AGUJA ",
    "CANULA PARA TRAQUEOSTOMIA  ADULTO  DE CLORURO DE POLIVINILO  CON BALON  CURVADA  CINTA DE FIJACION  GLOBO DE BAJA PRESION Y ALTO VOLUMEN  RADIOPACA  C",
    "SONDA PARA ALIMENTACION  DE PLASTICO TRANSPARENTE  ESTERIL Y DESECHABLE CON UN ORIFICIO EN EL EXTREMO PROXIMAL Y OTRO EN LOS PRIMEROS 2 CM  TAMANO: PR",
    "SONDA PARA DRENAJE  EN FORMA DE T  DE LATEX  TIPO: KEHR  CALIBRE: 12 FR",
    "SONDA PARA DRENAJE  EN FORMA DE T  DE LATEX  TIPO: KEHR  CALIBRE: 14 FR ",
    "SONDA PARA DRENAJE  EN FORMA DE T  DE LATEX  TIPO: KEHR  CALIBRE: 16 FR",
    "SONDA PARA DRENAJE  EN FORMA DE T  DE LATEX  TIPO: KEHR  CALIBRE: 18 FR",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 3 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  ESTERILES  DESECHABLES  CON GLOBO DE AUTORRETENCION DE 5 ML  CON VALVULA PARA JERINGA  TIPO: FOLEY DE DOS VIAS ",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  ESTERILES  DESECHABLES  CON GLOBO DE AUTORRETENCION DE 5 ML  CON VALVULA PARA JERINGA  TIPO: FOLEY DE DOS VIAS ",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA PARA DRENAJE URINARIO  DE LATEX  CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA  ESTERIL Y DESECHABLE  TIPO: FOLEY DE DOS VIAS  CA",
    "SONDA GASTROINTESTINALES DESECHABLES Y CON MARCA RADIOPACA  TIPO: LEVIN  CALIBRE: 14 FR ",
    "SONDA GASTROINTESTINALES DESECHABLES Y CON MARCA RADIOPACA  TIPO: LEVIN  CALIBRE: 16 FR ",
    "CEPILLO PARA LAVADO DE INSTRUMENTAL  CON CERDAS DE FIBRA VEGETAL  LECHUGUILLA ",
    "CEPILLO PARA USO QUIRURGICO  DE PLASTICO  DE FORMA RECTANGULAR  CON DOS AGARRADERAS LATERALES SIMETRICAS Y CERDAS DE NYLON ",
    "CERA PARA HUESOS (PASTA DE BECK) ESTERIL  SOBRE CON 2 5 G ",
    "CINTA METRICA  AHULADA  GRADUADA EN CENTIMETROS Y MILIMETROS  LONGITUD: 1 50 M ",
    "CINTA UMBILICALES  DE ALGODON  TEJIDO PLANO (TRENZADO DE 21 HILOS)  ESTERILES  LONGITUD: 41 CM  ANCHO: 4 MM ",
    "CINTA PARA ESTERILIZACION EN VAPOR A PRESION TAMANO: 18 MM X 50 M ",
    "CINTA MICROPOROSA  DE TELA NO TEJIDA  UNIDIRECCIONAL  DE COLOR BLANCO  CON RECUBRIMIENTOS ADHESIVOS EN UNA DE SUS CARAS LONGITUD: 10 M  ANCHO: 1 25 C",
    "CINTA MICROPOROSA  DE TELA NO TEJIDA  UNIDIRECCIONAL  DE COLOR BLANCO  CON RECUBRIMIENTOS ADHESIVOS EN UNA DE SUS CARAS LONGITUD: 10 M  ANCHO: 5 00 C",
    "CINTA MICROPOROSA  DE TELA NO TEJIDA  UNIDIRECCIONAL  DE COLOR BLANCO  CON RECUBRIMIENTOS ADHESIVOS EN UNA DE SUS CARAS  LONGITUD: 10M   ANCHO: 2 50 C",
    "CINTA MICROPOROSA  DE TELA NO TEJIDA  UNIDIRECCIONAL  DE COLOR BLANCO  CON RECUBRIMIENTOS ADHESIVOS EN UNA DE SUS CARAS LONGITUD: 10 M  ANCHO: 7 50 C",
    "CIRCUITO DE VENTILACION PARA ANESTESIA  DE POLIVINILO  CONSTA DE DOS MANGUERAS  UN FILTRO  CONEXION EN Y DE PLASTICO  CODO  MASCARILLA Y BOLSAS DE 3",
    "DESECHABLES DE PUNZO-CORTANTES  DE POLIPROPILENO  ESTERILIZABLE  INCINERABLE Y NO CONTAMINANTE  RESISTENTE A LA PERFORACION  AL IMPACTO Y A LA PERDIDA",
    "DESECHABLES DE PUNZO-CORTANTES  DE POLIPROPILENO  ESTERILIZABLE  INCINERABLE Y NO CONTAMINANTE  RESISTENTE A LA PERFORACION  AL IMPACTO Y A LA PERDIDA",
    "COMPRESA  PARA VIENTRE  DE ALGODON  CON TRAMA RADIOPACA  LONGITUD: 70 CM  ANCHO: 45 CM ",
    "ROPA QUIRURGICA PAQUETE PARA CESAREA Y CIRUGIA GENERAL   TELA NO TEJIDA DE POLIPROPILENO  IMPERMEABLE A LA PENETRACION DE LIQUIDOS Y FLUIDOS  COLOR A",
    "UNIFORMES (TRAJE)QUIRURGICOS DESECHABLES",
    "ROPA QUIRURGICA PAQUETE PARA PARTO  TELA NO TEJIDA DE POLIPROPILENO  IMPERMEABLE A LA PENETRACION DE LIQUIDOS Y FLUIDOS  COLOR ANTIRREFLEJANTE  NO TRA",
    "BATA QUIRURGICA CON PUNOS AJUSTABLES Y REFUERZO EN MANGAS Y PECHO  TELA NO TEJIDA DE POLIPROPILENO  IMPERMEABLE A LA PENETRACION DE LIQUIDOS Y FLUIDOS",
    "CONECTOR DE UNA VIA  DE PLASTICO  DESECHABLES  TIPO: SIMS  DELGADO ",
    "DE DOS VIAS EN (Y) DE PLASTICO  DESECHABLE ",
    "CONECTOR DE UNA VIA  DE PLASTICO  DESECHABLES  TIPO: SIMS  GRUESO",
    "CONTENEDOR DESECHABLE PARA LIQUIDOS  DE POLIPROPILENO DE COLOR AMARILLO  RIGIDO  ESTERILIZABLE  INCINERABLE Y NO CONTAMINANTE; RESISTENTE A LA PERFORA",
    "EQUIPOS PARA DRENAJE DE LA CAVIDAD PLEURAL  CON TRES CAMARAS PARA SELLO DE AGUA  SUCCION Y COLECCION DE LIQUIDOS  CON DOS VALVULAS DE SEGURIDAD DE ALT",
    "ELECTRODO DE BROCHE PARA MONITOREO CONTINUO DESECHABLE ADULTO CON PASTA CONDUCTIVA",
    "SUTURA SINTETICAS ABSORBIBLES DE POLIGLICONATO CON AGUJA LONGITUD DE LA HEBRA: 67-75 CM CALIBRE DE LA SUTURA: 0  CARACTERISTICAS DE LA AGUJA: 1/2 CIRC",
    "EQUIPO PARA APLICACION DE VOLUMENES MEDIDOS DE PLASTICO GRADO MEDICO  ESTERIL  DESECHABLE  CONSTA DE:BAYONETA  FILTRO DE AIRE  CAMARA BURETA FLEXIBL",
    "PARA VENOCLISIS  EN FORMA DE MARIPOSA (PEDIATRICO)  DE PLASTICO  ESTERIL Y DESECHABLE CONSTA DE: TUBO  ADAPTADOR Y MARIPOSA  CALIBRE DE LA AGUJA: 19 ",
    "CATETER PARA VENOCLISIS  EN FORMA DE MARIPOSA (PEDIATRICO)  DE PLASTICO  ESTERIL Y DESECHABLE  CONSTA DE: TUBO  ADAPTADOR Y MARIPOSA  CALIBRE DE LA AG",
    "PARA VENOCLISIS  EN FORMA DE MARIPOSA (PEDIATRICO)  DE PLASTICO  ESTERIL Y DESECHABLE CONSTA DE: TUBO  ADAPTADOR Y MARIPOSA  CALIBRE DE LA AGUJA: 23 ",
    "EQUIPO PARA DRENAJE POR ASPIRACION PARA USO POSTQUIRURGICO CONSTA DE: FUELLE SUCCIONADOR  SONDA CONECTORA  CINTA DE FIJACION  SONDA DE SUCCION MULTIP",
    "EQUIPO PARA DRENAJE POR ASPIRACION PARA USO POSTQUIRURGICO CONSTA DE: FUELLE SUCCIONADOR  SONDA CONECTORA  CINTA DE FIJACION  SONDA DE SUCCION MULTIP",
    "EQUIPO BASICO PARA BLOQUEO EPIDURAL  CONTIENE:- AGUJA TIPO TUOHY  CALIBRE 16 O 17G  LONGITUD DE 75 A 91 MM  CON ADAPTADOR LUER LOCK HEMBRA Y MANDRIL ",
    "EQUIPOS PARA HEMODIALISIS DE INSERCION EN SUBCLAVIA  YUGULAR O FEMORAL DOBLE LUMEN  INCLUYE:- UNA CANULA - UNA JERINGA DE 5 ML - UNA GUIA DE ACERO ",
    "EQUIPO EQUIPO PARA ANESTESIA EPIDURAL  CONTIENE:- AGUJA MODELO TUOHY CALIBRE 17G  LONGITUD 75-91 MM - SUJETADOR FILTRANTE DE 0 2 MICRAS O FILTRO EPI",
    "ESPEJO VAGINAL DESECHABLE  MEDIANO  VALVA SUPERIOR DE 10 7 CM  VALVA INFERIOR DE 12 0 CM  ORIFICIO CENTRAL DE 3 4 CM ",
    "ESPONJA NEUROQUIRURGICAS DE ALGODON PRENSADO O RAYON NO TEJIDO  CON MARCA RADIOPACA  ESTERILES MEDIDAS: 13 0 X 76 0 MM ",
    "GASA  SECA CORTADA  DE ALGODON LARGO: 7 5 CM  ANCHO:  5 CM ",
    "GASA  SECA CORTADA  DE ALGODON LARGO: 10 CM  ANCHO:  10 CM ",
    "GASA SIMPLE  SECA DE ALGODON  TIPO HOSPITAL ROLLO TEJIDO PLANO (DOBLADA) LARGO: 91 M   ANCHO: 91 CM ",
    "GASA SECA CORTADA  DE ALGODON CON MARCA RADIOPACA LARGO: 10 CM   ANCHO: 10 CM ",
    "GORRO DE TELA NO TEJIDA DE POLIPROPILENO  DESECHABLE  IMPERMEABLE A LA PENETRACION DE LIQUIDOS Y FLUIDOS; ANTIESTATICA Y RESISTENTE A LA TENSION  CINT",
    "GORRO REDONDO CON ELASTICO AJUSTABLE AL CONTORNO DE LA CARA  DE TELA NO TEJIDA DE POLIPROPILENO  DESECHABLE  IMPERMEABLE A LA PENETRACION DE LIQUIDOS ",
    "GUANTE NO ESTERIL MEDIANO",
    "GUANTE PARA CIRUGIA  DE LATEX NATURAL  ESTERILES Y DESECHABLES  TALLAS: 6 1/2",
    "GUANTE PARA CIRUGIA  DE LATEX NATURAL  ESTERILES Y DESECHABLES  TALLAS: 7",
    "GUANTE PARA CIRUGIA  DE LATEX NATURAL  ESTERILES Y DESECHABLES  TALLAS: 7 1/2",
    "GUANTE PARA CIRUGIA  DE LATEX NATURAL  ESTERILES Y DESECHABLES  TALLAS: 8",
    "GUANTE PARA CIRUGIA  DE LATEX NATURAL  ESTERILES Y DESECHABLES  TALLAS: 8 1/2",
    "GUANTES PARA EXPLORACION  AMBIDIESTRO  ESTERILES  DE LATEX  DESECHABLES  TAMANOS: CHICO ",
    "GUANTES PARA EXPLORACION  AMBIDIESTRO  ESTERILES  DE LATEX  DESECHABLES  TAMANOS: MEDIANO ",
    "GUANTES PARA EXPLORACION  AMBIDIESTRO  ESTERILES  DE LATEX  DESECHABLES  TAMANOS: GRANDE ",
    "GUATA DE TELA NO TEJIDA  DE ALGODON O FIBRAS DERIVADAS DE CELULOSA Y RESINAS LONGITUD: 5 M    ANCHO: 10 CM ",
    "GUATA DE TELA NO TEJIDA  DE ALGODON O FIBRAS DERIVADAS DE CELULOSA Y RESINAS LONGITUD: 5 M  ANCHO: 15 CM ",
    "GUATA DE TELA NO TEJIDA  DE ALGODON O FIBRAS DERIVADAS DE CELULOSA Y RESINAS LONGITUD: 5 M  ANCHO: 20 CM ",
    "HEMOSTATICOS ESPONJA HEMOSTATICA DE GELATINA O COLAGENO DE: 50 A 100 X 70 A 125 MM ",
    "GASA HEMOSTATICA ABSORBENTE SOLUBLE ",
    "SATIN HEMOSTATICO ABSORBIBLE ",
    "HOJA PARA BISTURI DE ACERO INOXIDABLE  EMPAQUEINDIVIDUAL  ESTERILY DESECHABLE  NO  12",
    "HOJA PARA BISTURI DE ACERO INOXIDABLE  EMPAQUEINDIVIDUAL  ESTERILY DESECHABLE  NO  11",
    "HOJA PARA BISTURI DE ACERO INOXIDABLE  EMPAQUEINDIVIDUAL  ESTERILY DESECHABLE  NO  15",
    "HOJA PARA BISTURI DE ACERO INOXIDABLE  EMPAQUEINDIVIDUAL  ESTERILY DESECHABLE  NO  21",
    "HOJA PARA BISTURI DE ACERO INOXIDABLE  EMPAQUEINDIVIDUAL  ESTERILY DESECHABLE  NO  23",
    "EQUIPO PARA VENOCLISIS SIN AGUJA  ESTERILES  DESECHABLES  MICROGOTERO ",
    "EQUIPO PARA VENOCLISIS SIN AGUJA  ESTERILES  DESECHABLES  NORMOGOTERO ",
    "PARA TRANSFUSION  CON FILTRO  SIN AGUJA ",
    "JABON NEUTRO  PASTILLA DE 100 G ",
    "JALEA LUBRICANTE  ASEPTICA  ",
    "JERINGA DE PLASTICO  SIN AGUJA CON PIVOTE TIPO LUER LOCK  ESTERILES Y DESECHABLES CAPACIDAD: 3 ML  ESCALA GRADUADA EN ML  DIVISIONES DE 0 5 Y SUBDIVI",
    "JERINGA DE PLASTICO  CON BULBO DE HULE  DESECHABLES CAPACIDAD: 60 ML ",
    "JERINGA DE PLASTICO  SIN AGUJA CON PIVOTE TIPO LUER LOCK ESTERILES Y DESECHABLES CAPACIDAD: 5 ML  ESCALA GRADUADA EN ML DIVISIONES DE 1 0 Y SUBDIVIS",
    "JERINGA DE PLASTICO  SIN AGUJA CON PIVOTE TIPO LUER LOCK ESTERILES Y DESECHABLES CAPACIDAD: 10 ML  ESCALA GRADUADA EN ML DIVISIONES DE 1 0 Y SUBDIVI",
    "JERINGA DE PLASTICO  SIN AGUJA CON PIVOTE TIPO LUER LOCK ESTERILES Y DESECHABLES CAPACIDAD: 20 ML  ESCALA GRADUADA EN ML DIVISIONES DE 5 0 Y SUBDIVI",
    "JERINGA DE PLASTICO  PARA TUBERCULINA  DE 1 ML DE CAPACIDAD  CON AGUJA DE 27 G X 13 MM CON ESCALA GRADUADA EN ML  CON DIVISIONES DE 0 1 Y SUBDIVISIONE",
    "JERINGA DE VIDRIO SIN AGUJA CON PIVOTE EXCENTRICO DE VIDRIO  REUTILIZABLES CAPACIDAD 50 ML Y ESCALA GRADUADA EN ML  CON DIVISIONES DE 10 0 Y SUBDIVI",
    "JERINGA DE VIDRIO  SIN AGUJA  CON PIVOTE METALICO  REUTILIZABLES  CAPACIDAD: 10 ML   ESCALA GRADUADA EN ML DIVISIONES DE 1 0 Y SUBDIVISIONES DE 0 2 ",
    "LLAVE DE TRES VIAS CON TUBO DE EXTENSION DE PLASTICO RIGIDO O EQUIVALENTE  CON TUBO DE EXTENSION DE CLORURO DE POLIVINILO DE 80 CM DE LONGITUD ",
    "LLAVE DE CUATRO VIAS SIN EXTENSION  DE PLASTICO ESTERIL Y DESECHABLE ",
    "MICRONEBULIZADORES C/MASCARILLA ADULTO",
    "MASCARILLA PARA ANESTECIA NO  0 CON CONECTOR Y COGIN",
    "MASCARILLA PARA ANESTECIA NO  2 CON CONECTOR Y COGIN",
    "MASCARILLA PARA ANESTESIA NO 4",
    "MASCARILLA PARA ANESTECIA NO  1 CON CONECTOR Y COGIN",
    "MASCARILLA PARA ANESTESIA NO 3",
    "MASCARILLA PARA ANESTESIA NO  5",
    "MICRONEBULIZADOR C/MASCARILLA PEDIATRICA",
    "MASCARILLA DESECHABLE  PARA ADMINISTRACION DE OXIGENO  CON TUBO DE CONEXION DE 180 CM Y ADAPTADOR ",
    "CUBREBOCA PARA USO DESECH  HOSPITALARIO",
    "PANAL DE FORMA ANATOMICA  DESECHABLES  PARA NINOS  MEDIDA: CHICO ",
    "PANAL PREDOBLADOS  DESECHABLES  PARA ADULTOS ",
    "GEL CONDUCTOR ELECTROLITICO  PARA ELECTROMIOGRAFIA  POTENCIALES EVOCADOS Y NEUROCONDUCCION MOTORA ",
    "PERILLA PARA ASPIRACION DE SECRECIONES  DE HULE  NO  4 ",
    "RASTRILLOS DE CABEZA FIJA  RECTANGULAR  DE 1 A 1 5 CM DE ANCHO Y DE 3 5 A 4 5 CM DE LONGITUD  CON BORDE LISO  BANDA LUBRICANTE  DOBLE HOJA DE AFEITAR ",
    "SISTEMA BAIN  COAXIAL PARA ANESTESIA CON CIRCUITO DE REINALACION PARCIAL SIN ABSORVEDOR DE CAL SOSADA  CONTIENE: UN SISTEMA COAXIAL CON ENTRADA PARA G",
    "SISTEMA BAIN DE VENTILACION PEDIATRICA CON BOSA RESERVORIO DE 1 LITRO Y VALVULA ",
    "CATETER PARA DRENAJE TORACICO  DE ELASTOMERO DE SILICON  RADIOPACA LONGITUD: 45 A 51 CM  CALIBRE: 36 FR ",
    "SONDA PARA YEYUNOSTOMIA  ESPECIAL PARA NUTRICION A LARGO PLAZO  DESECHABLE LONGITUD: 120 CM   CALIBRE: 24FR  ",
    "CATETER PARA DRENAJE TORACICO  DE ELASTOMERO DE SILICON  RADIOPACA LONGITUD: 45 A 51 CM  CALIBRE: 28 FR ",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE POLIPROPILENO  CON AGUJA  LONGITUD DE LA HEBRA: 45 CM  CALIBRE DE LA SUTURA: 6-0  CARACTERISTICAS D",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE POLIPROPILENO  CON AGUJA  LONGITUD DE LA HEBRA: 45 CM  CALIBRE DE LA SUTURA: 2-0  CARACTERISTICAS D",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE POLIPROPILENO  CON AGUJA  LONGITUD DE LA HEBRA: 60 CM  CALIBRE DE LA SUTURA: 7-0  CARACTERISTICAS D",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE POLIPROPILENO  CON AGUJA  LONGITUD DE LA HEBRA: 90 CM  CALIBRE DE LA SUTURA: 5-0  CARACTERISTICAS D",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE POLIPROPILENO  CON AGUJA  LONGITUD DE LA HEBRA: 90 CM  CALIBRE DE LA SUTURA: 4-0  CARACTERISTICAS D",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE POLIPROPILENO  CON AGUJA  LONGITUD DE LA HEBRA: 90 CM  CALIBRE DE LA SUTURA: 3-0  CARACTERISTICAS D",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE NYLON  CON AGUJA  LONGITUD DE LA HEBRA: 13 CM (NEGRO)  CALIBRE DE LA SUTURA: 8-0  CARACTERISTICAS D",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE NYLON  CON AGUJA  LONGITUD DE LA HEBRA: 8 A 13 CM (NEGRO)  CALIBRE DE LA SUTURA: 10-0  CARACTERISTI",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE NYLON  CON AGUJA  LONGITUD DE LA HEBRA: 45 CM  CALIBRE DE LA SUTURA: 4-0  CARACTERISTICAS DE LA AGU",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE NYLON  CON AGUJA  LONGITUD DE LA HEBRA: 45 CM  CALIBRE DE LA SUTURA: 3-0  CARACTERISTICAS DE LA AGU",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE NYLON  CON AGUJA  LONGITUD DE LA HEBRA: 45 CM  CALIBRE DE LA SUTURA: 2-0  CARACTERISTICAS DE LA AGU",
    "SUTURAS CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 A 75 CM  CALIBRE DE LA SUTURA: 2-0  CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO  AHUSADA (35-3",
    "SUTURAS CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 A 75 CM  CALIBRE DE LA SUTURA: 1  CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO  AHUSADA (35-37 ",
    "SUTURA SEDA NEGRA TRENZADA  CON AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 5-0  1/2 CIRCULO AHUSADA (20-25 MM) ",
    "SUTURA SEDA NEGRA TRENZADA  CON AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 3-0  CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (25-26",
    "SUTURA SEDA NEGRA TRENZADA  CON AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 2-0  CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (25-26",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE POLIPROPILENO  CON AGUJA  LONGITUD DE LA HEBRA: 90 CM  CALIBRE DE LA SUTURA: 3-0  CARACTERISTICAS D",
    "SUTURA SEDA NEGRA TRENZADA  CON AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 2-0  CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (35-37",
    "SUTURA SEDA NEGRA TRENZADA  SIN AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 4-0 ",
    "SUTURA SEDA NEGRA TRENZADA SIN AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 3-0",
    "SUTURA SEDA NEGRA TRENZADA  SIN AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 2-0 ",
    "SUTURA SEDA NEGRA TRENZADA SIN AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 0",
    "SUTURA SEDA NEGRA TRENZADA SIN AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 1",
    "SUTURA SINTETICAS ABSORBIBLES POLIMERO DE ACIDO GLICOLICO TRENZADO  CON AGUJA  LONGITUD DE LA HEBRA:67-70 CM  CALIBRE DE LA SUTURA: 3-0 CARACTERISTICA",
    "SUTURA SINTETICAS ABSORBIBLES POLIMERO DE ACIDO GLICOLICO TRENZADO CON AGUJA  LONGITUD DE LA HEBRA: 67-70 CM CALIBRE DE LA SUTURA: 1 CARACTERISTICAS D",
    "SUTURA SINTETICAS ABSORBIBLES POLIMERO DE ACIDO GLICOLICO TRENZADO CON AGUJA  LONGITUD DE LA HEBRA: 67-70 CM CALIBRE DE LA SUTURA: 0 CARACTERISTICAS D",
    "SUTURA SINTETICAS ABSORBIBLES POLIMERO DE ACIDO GLICOLICO TRENZADO CON AGUJA QUIRURGICAS CIERRE Y APROXIMACION DE LOS BORDES DE UNA HERIDA A FIN DE FA",
    "SUTURA SINTETICAS NO ABSORBIBLES DE POLIESTER TRENZADO CON RECUBRIMIENTO CON AGUJA QUIRURGICAS LONGITUD DE LA HEBRA: 75 CM CALIBRE DE LA SUTURA: 5 CAR",
    "SUTURA SINTETICAS NO ABSORBIBLES DE POLIESTER TRENZADO CON RECUBRIMIENTO CON AGUJA LONGITUD DE LA HEBRA: 75 CM CALIBRE DE LA SUTURA 5 CARACTERISTICAS ",
    "SUTURA SINTETICAS NO ABSORBIBLES DE POLIESTER TRENZADO CON RECUBRIMIENTO CON AGUJA LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 2 CARACTERISTICA",
    "SUTURA SEDA NEGRA TRENZADA CON AGUJA LONGITUD DE LA HEBRA: 75 CM CALIBRE DE LA SUTURA: 1 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (35-37 MM)",
    "SUTURA SEDA NEGRA TRENZADA CON AGUJA  LONGITUD DE LA HEBRA: 75 CM  CALIBRE DE LA SUTURA: 0 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (25-26 MM)",
    "SUTURA SINTETICAS ABSORBIBLES MONOFILAMENTO DE POLIDIOXANONA CON AGUJA LONGITUD DE LA HEBRA: 70 CM CALIBRE DE LA SUTURA: 0  CARACTERISTICAS DE LA AGUJ",
    "SUTURA SINTETICAS NO ABSORBIBLES MONOFILAMENTO DE NYLON CON AGUJA LONGITUD DE LA HEBRA: 45 CM CALIBRE DE LA SUTURA: 6-0 CARACTERISTICAS DE LA AGUJA: 3",
    "SUTURA CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 CM CALIBRE DE LA SUTURA: 5-0CARACTERISTICAS DE LA AGUJA:1/2 CIRCULO AHUSADA (19-20 MM) ",
    "SUTURAS CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 A 75 CM CALIBRE DE LA SUTURA: 0 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (35-37 MM)",
    "SUTURA CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 A 75 CM CALIBRE DE LA SUTURA: 2-0 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (25-27 MM",
    "SUTURA CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 A 75 CM CALIBRE DE LA SUTURA: 0 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (25-27 MM) ",
    "SUTURA CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 A 75 CM CALIBRE DE LA SUTURA: 3-0 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (25-27 MM",
    "SUTURA CATGUT CROMICO CON AGUJA  LONGITUD DE LA HEBRA: 68 A 75 CM CALIBRE DE LA SUTURA: 4-0 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCULO AHUSADA (25-27 MM",
    "SUTURA SINTETICAS ABSORBIBLES DE POLIGLICONATO CON AGUJA LONGITUD DE LA HEBRA:67-75 CM CALIBRE DE LA SUTURA: 4-0 CARACTERISTICAS DE LA AGUJA:1/2 CIRCU",
    "SUTURA SINTETICAS ABSORBIBLES DE POLIGLICONATO CON AGUJA LONGITUD DE LA HEBRA: 67-75 CM CALIBRE DE LA SUTURA: 3-0 CARACTERISTICAS DE LA AGUJA: 1/2 CIR",
    "SUTURA SINTETICAS ABSORBIBLES DE POLIGLICONATO CON AGUJA LONGITUD DE LA HEBRA:67-75 CM  CALIBRE DE LA SUTURA: 2-0 CARACTERISTICAS DE LA AGUJA:1/2 CIRC",
    "SUTURA SINTETICAS ABSORBIBLES DE POLIGLICONATO CON AGUJA LONGITUD DE LA HEBRA:67-75 CM CALIBRE DE LA SUTURA: 3-0 CARACTERISTICAS DE LA AGUJA:1/2 CIRCU",
    "SUTURA SINTETICAS ABSORBIBLES DE POLIGLICONATO CON AGUJA LONGITUD DE LA HEBRA:67-75 CM CALIBRE DE LA SUTURA: 0 CARACTERISTICAS DE LA AGUJA:1/2 CIRCULO",
    "SUTURA SINTETICAS ABSORBIBLES DE POLIGLICONATO CON AGUJA LONGITUD DE LA HEBRA: 67-75 CM CALIBRE DE LA SUTURA: 0 CARACTERISTICAS DE LA AGUJA: 1/2 CIRCU",
    "SUTURA DE POLIESTER BLANCO TRENZADO DOBLE ARMADO CON AGUJA ESPATULADA DE 1/4 DE CIRCULO LONGITUD DE LA AGUJA DE 8 A 13 MM LONGITUD DE LA HEBRA 45 CM  ",
    "SUTURA DE MONOFILAMENTO SINTETICO ABSORBIBLE DE COPOLIMERO DE GLICOLIDA Y EPSILON-CAPROLACTONA CON COLOR  LONGITUD DE LA HEBRA: 70 CM CALIBRE DE LA SU",
    "SINTETICAS NO ABSORBIBLES MONOFILAMENTO DE POLIPROPILENO CON AGUJA LONGITUD DE LA HEBRA:75 CM CALIBRE DE LA SUTURA: 1 CARACTERISTICAS DE LA AGUJA: 1/2",
    "TAPONES LUER LOCK PARA CATETER DE HICKMAN PARA HEPARINIZACION ESTERIL Y DESECHABLE ",
    "TELA DE ACETATO CON ADHESIVO EN UNA DE SUS CARAS  LONGITUD: 10 M ANCHO: 2 50 CM",
    "TELAS ADHESIVAS DE ACETATO CON ADHESIVO EN UNA DE SUS CARAS LONGITUD: 10 M ANCHO: 5 00 CM",
    "TELA DE ACETATO CON ADHESIVO EN UNA DE SUS CARAS LONGITUD: 10 M ANCHO: 7 50 CM ",
    "TERMOMETRO CLINICO DE VIDRIO TRANSPARENTE CON MERCURIO QUIMICAMENTE PURO ESCALA GRADUADA EN GRADOS CENTIGRADOS (35 5oC A 41oC) CON SUBDIVISIONES EN ",
    "TERMOMETRO CLINICO DE VIDRIO TRANSPARENTE CON MERCURIO QUIMICAMENTE PURO ESCALA GRADUADA EN GRADOS CENTIGRADOS (35 5 oC A 41o C) CON SUBDIVISIONES EN ",
    "TOALLA PARA GINECO-OBSTETRICIA  RECTANGULARES CONSTITUIDAS POR CUATRO CAPAS DE MATERIAL ABSORBENTE DESECHABLES ",
    "TUBO PARA CANALIZACION DE LATEX NATURAL RADIOPACO LONGITUD 45 CM DIAMETRO: 7 94 MM (5/16) ",
    "TUBO PARA CANALIZACION DE LATEX NATURAL RADIOPACO LONGITUD 45 CM DIAMETRO: 12 70 MM (1/2) ",
    "TUBO PARA CANALIZACION DE LATEX NATURAL RADIOPACO LONGITUD 45 CM DIAMETRO: 19 05 MM (3/4) PENROSE",
    "TUBO PARA CANALIZACION DE LATEX NATURAL RADIOPACO LONGITUD 45 CM DIAMETRO: 25 40 MM (1)",
    "TUBO PARA TORNIQUETE DE LATEX COLOR AMBAR CON ESPESOR DE LA PARED DE 1 13 A 1 37 MM ",
    "TUBO PARA ASPIRADOR DE HULE LATEX COLOR AMBAR DIAMETRO INTERNO 6 3 MM ESPESOR DE PARED 3 77 MM",
    "VALVULA PARA DERIVACION DE LIQUIDO CEFALORRAQUIDEO DE RESORTE PRESION MEDIA DE 80 A 120 MM DE H2O CATETER CEFALICO O VENTRICULAR DE 15 CM MINIMO DE LO",
    "VALVULA PARA DERIVACION DE LIQUIDO CEFALORRAQUIDEO DE RESORTE PRESION ALTA DE 120 A 170 MM DE H2O CATETER CEFALICO O VENTRICULAR DE 15 CM MINIMO DE LO",
    "VALVULA PARA DERIVACION DE LIQUIDO CEFALORRAQUIDEO DE RESORTE PRESION BAJA DE 40 A 80 MM DE H2O CATETER CEFALICO O VENTRICULAR DE 15 CM MINIMO DE LONG",
    "VALVULA PARA DERIVACION DE LIQUIDO CEFALORRAQUIDEO DE RESORTE PRESION MEDIA DE 80 A 120 MM DE H2O CATETER CEFALICO O VENTRICULAR DE 15 CM MINIMO DE LO",
    "ELASTICA ADHESIVA DE ALGODON Y FIBRA SINTETICA CON ADHESIVO EN UNA DE SUS CARAS LONGITUD 27 M ANCHO  7 5 CM ",
    "VENDA DE GOMA (SMARCH) DE HULE NATURAL GRADO MEDICO LONGITUD 2 7 M ANCHO: 8 CM",
    "VENDA ENYESADAS DE GASA DE ALGODON RECUBIERTAS DE UNA CAPA UNIFORME DE YESO GRADO MEDICO LONGITUD: 2 75 M ANCHO: 5 CM",
    "VENDA ENYESADAS DE GASA DE ALGODON RECUBIERTAS DE UNA CAPA UNIFORME DE YESO GRADO MEDICO LONGITUD 2 75 M ANCHO: 10 CM",
    "VENDA ENYESADAS DE GASA DE ALGODON RECUBIERTAS DE UNA CAPA UNIFORME DE YESO GRADO MEDICO LONGITUD: 2 75 M ANCHO: 15 CM",
    "VENDA ENYESADAS DE GASA DE ALGODON RECUBIERTAS DE UNA CAPA UNIFORME DE YESO GRADO MEDICO LONGITUD: 2 75 M ANCHO: 20 CM",
    "VENDA DE MALLA ELASTICA  FORMA TUBULAR  LONGITUD: 100 M NUMERO: 1 ",
    "VENDA DE MALLA ELASTICA FORMA TUBULAR LONGITUD: 100 M NUMERO: 2 ",
    "VENDA DE MALLA ELASTICA  FORMA TUBULAR  LONGITUD: 100 M  NUMERO: 3 ",
    "VENDA DE MALLA ELASTICA FORMA TUBULAR LONGITUD 100 M NUMERO 4",
    "VENDA ELASTICAS DE TEJIDO PLANO DE ALGODON CON FIBRAS SINTETICAS LONGITUD: 5 M ANCHO: 30 CM ",
    "VENDA ELASTICAS DE TEJIDO PLANO DE ALGODON CON FIBRAS SINTETICAS LONGITUD 5 M ANCHO 5 CM ",
    "VENDA ELASTICAS DE TEJIDO PLANO DE ALGODON CON FIBRAS SINTETICAS LONGITUD: 5 M ANCHO: 10 CM ",
    "VENDA ELASTICAS DE TEJIDO PLANO DE ALGODON CON FIBRAS SINTETICAS LONGITUD: 5 M ANCHO: 15 CM",
    "COLLARINES TIPO: FILADELFIA EVITA MOVIMIENTOS DE FLEXION DORSAL VENTRAL Y LATERALES ELABORADO EN ESPUMA PLASTICA BIVALVO CON ORIFICIOS PARA VENTILACIO",
    "PAPEL PARA ENVOLTURA KRAFT DE 70 KG Y 45 CM DE ANCHO",
    "CATETER TORAXICO N 16 FR",
    "CATETER TORAXICO NO 34 FR (SONDA ENDOPLEURAL)",
    "EQUIPO RESUCITADOR AMBU ADULTO",
    "MASCARILLA PARA OXIGENO PEDIATRICO",
    "PLEUROVAC SELLO DE AGUA(PEDIATRICO)",
    "LIMAS K # 15",
    "LIMAS K # 20",
    "LIMAS # 10",
    "DIQUES GRANDES 6X6T",
    "FRESA CARBURO NUM 2",
    "FRESA REDONDA CARBURO NUM 4",
    "FRESA REDONDA CARBURO NUM 6",
    "FRESA REDONDO CARBURO NUM 8",
    "LIQUIDO FIJADOR",
    "LIQUIDO REVELADOR",
    "RADIOGRAFIAS PERIAPICAL ADULTO",
    "DIQUES CHICOS 5X5 T",
    "ALVEOGYL",
    "ACEITE LUBRICANTE PARA TURBINA DE PIEZA DE MANO DE ALTA VELOCIDAD APLICADOR EN FORMA DE JERINGA ENVASE CON 2 ML",
    "ROLLOS DE ALGODON",
    "AMALGAMA CAPSULA",
    "ONZAS DE AMALGAMA",
    "AMALGAMADOR",
    "EUGENOL ENVASE CON 30 ML",
    "CEMENTO IONOMERO DE VIDRIO I PARA CEMENTACIONES DEFINITIVAS JUEGO",
    "CEMENTO IONOMERO DE VIDRIO RESTAURATIVO II COLOR NO 21 ESTUCHE",
    "HIDROXIDO DE CALCIO",
    "PROTECTOR PULPAR PARA SELLAR CAVIDADES DENTALES DE HIDROXIDO DE CALCIO COMPUESTO AUTOPOLIMERIZABLE DOS PASTAS SEMILIQUIDAS BASE 13 G Y CATALIZADOR 11 ",
    "CEMENTO DENTALES PARA RESTAURACION INTERMEDIA DE OXIDO DE ZINC (POLVO) 38 G Y EUGENOL (LIQUIDO) 14 ML CON GOTERO DE PLASTICO JUEGO",
    "CEMENTODENTALES PARA USO QUIRURGICO  DE OXIDO DE ZINC CON ENDURECEDOR (POLVO) 65 G Y EUGENOL (LIQUIDO) 30 ML CON GOTERO DE PLASTICO EQUIPO",
    "FRESA DIAMANTE NUM BR 46",
    "FRESA REDONDA CARBURO 1/4",
    "FRESA DIAMANTE NUM BR 45",
    "FRESA DIAMANTE NUM BR 41",
    "FRESA RUEDA DE CARRO DIAMANTE",
    "FRESAS DIAMANTE NUM BR 49",
    "FRESAS QUIRURGICAS # 703",
    "FRESA QUIRURGICA #702",
    "FRESAS QUIRURGICAS # 702",
    "FRESA REDONDA CARBURO NUM 3",
    "FRESA REDONDA CARBURO NUM 5",
    "FRESA QUIEURGICA #701",
    "FRESAS QUIRURGICAS # 701",
    "FRESA CILINDRICA DIAMANTE",
    "FRESA COLINDRICA DIAMANTE",
    "FRESA REDONDA CARBURO 1/2",
    "FRESA REDONDA CARBURO 1",
    "FRESA CARBURO NUM FG34",
    "JERINGA HIPODERMICA REUTILIZABLE PARA CARTUCHO ANESTESICO TIPO: CARPULE PIEZA",
    "RESINA SOLIDA A2",
    "RESINA SOLIDA A1",
    "RESINA FLUIDA A3",
    "RESINA FLUIDA A2",
    "SOLDADURA DE PLATA PARA USO DENTAL DE 0 40 MM  ROLLO DE 10 G ",
    "FORMOCRESOL",
    "MERCURIO TRIDESTILADO QUIMICAMENTE PURO ENVASE CON 250 G ",
    "PASTA PROFILACTICA",
    "PUNTAS DE GUTAPERCHA PARA OBTURACION DE CONDUCTOS RADICULARES  NUMEROS:45 A 80 (DE 5 EN 5)  ENVASE CON 200 GUTAPERCHA 2 DA  SERIE",
    "PUNTAS DE GUTAPERCHA PARA OBTURACION DE CONDUCTOS RADICULARES  NUMEROS: 10 A 40 (DE 5 EN 5) ",
    "HILO SEDA DENTAL SIN CERA ENVASE CON ROLLO DE 50 M ",
    "SUTURA SINTETICAS NO ABSORBIBLES MONOFILAMENTO DE NYLON CON AGUJA LONGITUD DE LA HEBRA:45 CM CALIBRE DE LA SUTURA: 5-0 CARACTERISTICAS DE LA AGUJA: 3/",
    "SUTURA SEDA 3-0",
    "SUTURA SINTETICAS NO ABSORBIBLES  MONOFILAMENTO DE NYLON  CON AGUJA LONGITUD DE LA HEBRA 45 CM CALIBRE DE LA SUTURA: 6-0 CARACTERISTICAS DE LA AGUJA: ",
    "SUTURA DE MONOFILAMENTO SINTETICO ABSORBIBLE DE COPOLIMERO DE GLICOLIDA Y EPSILON-CAPROLACTONA  CON COLOR LONGITUD DE LA HEBRA 45 CM CALIBRE DE LA SUT",
    "SUTURA DE MONOFILAMENTO SINTETICO ABSORBIBLE DE COPOLIMERO DE GLICOLIDA Y EPSILON-CAPROLACTONA CON COLOR LONGITUD DE LA HEBRA 45 CM CALIBRE DE LA SUTU",
    "EYECTORES DESECHABLES",
    "LIMAS # 8",
    "LIMAS K # 40 ",
    "LIMA K 1 SERIE PARA PULPOTOMIA PEDIATRICAS 12MM",
    "LIMA K1 SERIE PARA ENDO PEDIATRICAS 12MM",
    "AGUJA CORTA DE 30X21MM",
    "ANESTESICO TOPICO",
    "PUNTAS DE PAPEL 1RA SERIE",
    "MICROBRUSH",
    "CARRETE DE ALAMBRE LIGADURA  012",
    "PARAMONOFORMOCRESOL ALCANFORADO",
    "CARRETE DE ALAMBRE LIGADURA  018",
    "ARCO BARRA DE ERICH",
    "SEPARADOR OBWEGESER PARA CUERPO MANDIBULAR",
    "SEPARADOR DE RAMA MANDIBULAR (DEWIMED)",
    "GUANTES EXT-CHICOS",
    "AGUA DESTILADA  BIDON 20 LITROS",
    "AGUJA EXTRACORTA",
    "BOLSAS PARA ESTILIZAR 90X230MM (3 1/2 X10)",
    "GUTAPERCHA FINE FINE",
    "LIMAS K # 6",
    "LIMAS K # 10",
    "LIMAS K 2 DA SERIE",
    "SPIDEX SILICON",
    "FRESA ENDO-Z",
    "FRESA GATE # 1",
    "FRESA GATE #2",
    "FRESA GATE # 3",
    "TOPES PARA LIMA DE ENDODONCIA",
    "FRESA DIATECH FLAMA 852 DIAMANTE 198-199",
    "FRESA DIATECH PERA 830 DIAMANTE 049-052",
    "FRESA DATECH OCLUSAL 811 DIAMANTE 028",
    "FRESA DATECH TBALL 368 DIAMANTE 033",
    "REMOVEDOR DE SARRO",
    "FLORURO EN GEL",
    "EXPLORADOR",
    "CANULAS DE METAL ",
    "ACIDO GRAVADOR",
    "METRONIDAZOL 500MG  C/30TABS",
    "VALPROATO de magnesio c/40 tab 200 mg   ",
    "SUCRALFATO c/40 tabletas 1grs          ",
    "NITROFURANTOINA c/40 caps 100 mg        ",
    "AMOXICILINA/clavulanico c/12 tab 500/125",
    "RIFAMPICINA susp oral 100 mg/5 ml fco   ",
    "RIFAMPICINA c/isoniazida 300mg/400mg ",
    "RIFAMPICINA+isoniazida+pirazinamida+etam",
    "VITAMINA E c/100 o 99 grageas 400 mg    ",
    "METRONIDAZOL c/20 o 30 tab 500mg        ",
    "METRONIDAZOL c/10 ovulos vag 500mg      ",
    "ALBENDAZOL c/2 tabletas                 ",
    "ALBENDAZOL envase c/20 ml               ",
    "ENOXAPARINA sol iny40mg/0.4ml 2jgas    ",
    "HIERRO dextran sol iny 100mg/2ml c/3 amp",
];
</script>
<link rel="stylesheet" type="text/css" href="css/style.css"/>
<link rel="stylesheet" type="text/css" href="css/botones.css"/>
<style type="text/css">
    body {
        background-color: #F9F9F9;
    }
</style>
<title>Sistema de Captura de Invetarios</title>
</head>
<body onLoad="focus_locus();">

<form style="margin:0px" name="form1">

    <div style="width: 800px; margin: 50px auto;" class="letra">

        <H1><img src="images/gnkl.jpg"/>
            Captura de Inventario</H1>

        <p>Operador:
            <input type="text" value="<%=ope%>" name="op" id="op" size="15" readonly/>
            Unidad: <input type="text" value="<%=uni%>" name="uni" id="uni" size="45" readonly/>Clave: <input
                    type="text" value="<%=cv_uni%>" name="cv_uni" id="cv_uni" size="10" readonly/>
        </p>
    </div>
    <div style="height:20px; background-color:#4979F8; margin-bottom:25px;"><a href="index.jsp"
                                                                               class="boton red medium">Salir</a></div>
    <div style="margin:auto; background-color:#FFFFFF; width:800px; padding:10px;">
        <div style="width: 800px; margin:auto; background-color:#FFFFFF; margin:auto;" class="letra">
            ID Inventario:<input type="text" name="cv_inv" value="<%=cv_inv%>" size="15" readonly/><input type="text"
                                                                                                          name="tipo"
                                                                                                          value="<%=tipo%>"
                                                                                                          hidden="true"
                                                                                                          style="visibility:hidden"/><br/><br/>
            <table align="center">
                <tr>
                    <td>Clave</td>
                    <td><input type="text" value="" name="clave_med" id="clave_med" size="15"/> <input type="submit"
                                                                                                       name="submit"
                                                                                                       value="Clave"/>
                        <br/><input type="text" id="country" name="country" class="input_text"/><input type="submit"
                                                                                                       name="submit"
                                                                                                       value="Descripcion"/>
                    </td>
                    <td><!--Descripcion<input type="text" id="country" name="country" class="input_text"/--></td>
                    <td>&nbsp;</td>
                    <td><a href="gnr_inven.jsp?inv=<%=cv_inv%>" target="_blank"><img src="images/excel.png"/></a></td>
                </tr>
                <tr>
                    <td>Descripcion</td>
                    <td><input type="text" value="<%=descrip%>" name="descrip" id="descrip" size="60" readonly/></td>
                    <td>Clave</td>
                    <td><input type="text" value="<%=clave%>" name="clave" id="clave" size="15" readonly/></td>
                </tr>
                <tr>
                    <td>Presentacion</td>
                    <td><input type="text" value="<%=present%>" name="present" id="present" size="60" readonly/></td>
                    <td>Tipo</td>
                    <td><input type="text" value="<%=id_med%>" name="tipo" id="tipo" size="15" readonly/></td>
                </tr>
            </table>
        </div>
    </div>
</form>
<div style="width: 800px; margin: 50px auto; margin:auto; background-color:#FFFFFF; width:800px; padding:10px;"
     class="letra">
    <form style="margin:0px" name="form2">
        <table align="center">
            <tr>
                <td width="144">
                </td>
                <td>
                    <div style="visibility:hidden"><input type="text" value="<%=descrip%>" name="descrip" id="descrip"
                                                          readonly hidden="true"/>
                        <input type="text" value="<%=clave%>" name="clave" id="clave" size="15" readonly hidden="true"/>
                        <input type="text" value="<%=present%>" name="present" id="present" readonly hidden="true"/>
                        <input type="text" value="<%=cv_uni%>" name="cv_uni" id="cv_uni" size="10" readonly
                               hidden="true"/>
                        <input type="text" value="<%=id_med%>" name="tipo_med" id="tipo_med" readonly="readonly"
                               hidden="true"/>
                        <input type="text" value="<%=ope%>" name="op" id="op" readonly="readonly" hidden="true"/>
                        <input type="text" value="<%=uni%>" name="uni" id="uni" readonly="readonly"
                               hidden="true"/><input type="text" name="cv_inv" value="<%=cv_inv%>" size="15" readonly
                                                     hidden="true"/><input type="text" name="tipo" value="<%=tipo%>"
                                                                           hidden="true"/></div>
                </td>
            </tr>
            <tr>
                <td>Cantidad:</td>
                <td width="544"><input type="text" value="" name="cant" id="cant" size="15"
                                       onKeyPress="tufuncion(event)"/></td>
            </tr>
            <tr>
                <td><%
                    if (tipo.equals("cant")) {
                    } else {
                        out.print("Lote:");
                    }
                %><%%></td>
                <td><%if (tipo.equals("cant")){}else{out.print("<input type='text' value='' name='lote' id='lote' size='15' />");}%>
                        <%if (tipo.equals("cant")){}else{out.print("Caducidad:");};%>
                        <%if (tipo.equals("cant")){}else{out.print("<input type='text' value='' name='cadu' id='cadu' size='15' /></td>");}%>
                <td width="6">&nbsp;</td>
                <td width="66"><input type="submit" name="submit" id="Capturar" value="Capturar"/></td>
            </tr>
        </table>
    </form>
</div>
<div style="width: 800px; margin:auto; padding:10px; background-color:#FFFFFF" class="letra">
    <table align="center">
        <tr>
            <td></td>
            <td>Calve</td>
            <td><%
                if (tipo.equals("cant")) {
                } else {
                    out.print("Caduca");
                }
            %></td>
            <td><%
                if (tipo.equals("cant")) {
                } else {
                    out.print("Lote");
                }
            %></td>
            <td>Cantidad</td>
        </tr>
        <%
            String i_clave = "", i_caduc = "", i_lote = "", i_cant = "", i_id = "";
            String qry_inven = "select * from inventarios where clave_inv= '" + clave_inventario + "'";
            rset = stmt.executeQuery(qry_inven);
            while (rset.next()) {
                i_clave = rset.getString("clave");
                i_caduc = rset.getString("fecha_cad");
                i_lote = rset.getString("lote");
                i_cant = rset.getString("cantidad");
                i_id = rset.getString("id");
        %>
        <tr>
            <td>
                <a href="eliminar_registro.jsp?id=<%=i_id%>&ope=<%=ope%>&uni=<%=uni%>&cv_uni=<%=cv_uni%>&cv_inv=<%=cv_inv%>&tipo=<%=tipo%>"/><img
                    src="images/Delete.png" width="20" height="20"/></a></td>
            <td><input type="text" value="<%=i_clave%>" readonly/></td>
            <td><input type="text" value="<%=i_caduc%>" readonly  <%
                if (tipo.equals("lote")) {
                } else {
                    out.print("style='visibility:hidden'");
                }
            %> /></td>
            <td><input type="text" value="<%=i_lote%>" readonly <%
                if (tipo.equals("lote")) {
                } else {
                    out.print("style='visibility:hidden'");
                }
            %> /></td>
            <td><input type="text" value="<%=i_cant%>" readonly/></td>
        </tr>
        <%
            }
        %>
    </table>
</div>
</body>
<script>

    $(function () {

        $("#country").autocomplete(
                {
                    source: data
                });

    });

</script>
</html>